// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import "KHRequest.h"
#import "KHResponse.h"
#import <Foundation/Foundation.h>
@class KHRequestListener;
@class KHResponseListener;


@protocol KHHttpClient

/**
 * Synchronously send the given request.
 * Not thread-safe! Use a separate HttpClient instance per thread.
 *
 * * timeout in milliseconds or 0 for no timeout
 * * requestListener must be non-null if method is PATCH, POST or PUT
 * * responseListener may be null
 */
- (nonnull KHResponse *)sendRequest:(nonnull KHRequest *)request
                          timeoutMs:(int32_t)timeoutMs
                    requestListener:(nullable KHRequestListener *)requestListener
                   responseListener:(nullable KHResponseListener *)responseListener;

@end
