// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import "KHHttpHeader+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace ObjCpp { namespace Kullo { namespace Http {

auto HttpHeader::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.key),
            ::djinni::String::toCpp(obj.value)};
}

auto HttpHeader::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[KHHttpHeader alloc] initWithKey:(::djinni::String::fromCpp(cpp.key))
                                       value:(::djinni::String::fromCpp(cpp.value))];
}

} } }  // namespace ObjCpp::Kullo::Http
