// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import <Foundation/Foundation.h>

@interface KHHttpHeader : NSObject
- (nonnull instancetype)initWithKey:(nonnull NSString *)key
                              value:(nonnull NSString *)value;
+ (nonnull instancetype)HttpHeaderWithKey:(nonnull NSString *)key
                                    value:(nonnull NSString *)value;

@property (nonatomic, readonly, nonnull) NSString * key;

@property (nonatomic, readonly, nonnull) NSString * value;

@end
