// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import <Foundation/Foundation.h>
@protocol KHHttpClient;


@protocol KHHttpClientFactory

- (nullable id<KHHttpClient>)createHttpClient;

/** Returns pairs of <library name, version number> for the libraries used. */
- (nonnull NSDictionary<NSString *, NSString *> *)versions;

@end
