// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import "KHHttpHeader.h"
#include "kulloclient/http/HttpHeader.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KHHttpHeader;

namespace ObjCpp { namespace Kullo { namespace Http {

struct HttpHeader
{
    using CppType = ::Kullo::Http::HttpHeader;
    using ObjcType = KHHttpHeader*;

    using Boxed = HttpHeader;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} } }  // namespace ObjCpp::Kullo::Http
