// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import "KHHttpClient+Private.h"
#import "KHHttpClient.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "KHRequest+Private.h"
#import "KHRequestListener+Private.h"
#import "KHResponse+Private.h"
#import "KHResponseListener+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace ObjCpp { namespace Kullo { namespace Http {

class HttpClient::ObjcProxy final
: public ::Kullo::Http::HttpClient
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::ObjCpp::Kullo::Http::HttpClient;
public:
    using ObjcProxyBase::ObjcProxyBase;
    ::Kullo::Http::Response sendRequest(const ::Kullo::Http::Request & c_request, int32_t c_timeoutMs, const std::shared_ptr<::Kullo::Http::RequestListener> & c_requestListener, const std::shared_ptr<::Kullo::Http::ResponseListener> & c_responseListener) override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() sendRequest:(::ObjCpp::Kullo::Http::Request::fromCpp(c_request))
                                                                              timeoutMs:(::djinni::I32::fromCpp(c_timeoutMs))
                                                                        requestListener:(::djinni::Optional<boost::optional, ::ObjCpp::Kullo::Http::RequestListener>::fromCpp(c_requestListener))
                                                                       responseListener:(::djinni::Optional<boost::optional, ::ObjCpp::Kullo::Http::ResponseListener>::fromCpp(c_responseListener))];
            return ::ObjCpp::Kullo::Http::Response::toCpp(objcpp_result_);
        }
    }
};

} } }  // namespace ObjCpp::Kullo::Http

namespace ObjCpp { namespace Kullo { namespace Http {

auto HttpClient::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto HttpClient::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

} } }  // namespace ObjCpp::Kullo::Http
