// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import "KHRequest.h"


@implementation KHRequest

- (nonnull instancetype)initWithMethod:(KHHttpMethod)method
                                   url:(nonnull NSString *)url
                               headers:(nonnull NSArray *)headers
{
    if (self = [super init]) {
        _method = method;
        _url = [url copy];
        _headers = headers;
    }
    return self;
}

+ (nonnull instancetype)RequestWithMethod:(KHHttpMethod)method
                                      url:(nonnull NSString *)url
                                  headers:(nonnull NSArray *)headers
{
    return [[self alloc] initWithMethod:method
                                    url:url
                                headers:headers];
}

@end
