// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import <Foundation/Foundation.h>


@interface KHRequestListener : NSObject

- (nonnull NSData *)read:(int64_t)maxSize;

@end
