// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#include "kulloclient/http/ResponseListener.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KHResponseListener;

namespace ObjCpp { namespace Kullo { namespace Http {

class ResponseListener
{
public:
    using CppType = std::shared_ptr<::Kullo::Http::ResponseListener>;
    using ObjcType = KHResponseListener*;

    using Boxed = ResponseListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Http

