// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import "KHHttpHeader.h"
#import "KHResponseError.h"
#import <Foundation/Foundation.h>

@interface KHResponse : NSObject
- (nonnull instancetype)initWithError:(nullable NSNumber *)error
                           statusCode:(int32_t)statusCode
                              headers:(nonnull NSArray *)headers;
+ (nonnull instancetype)ResponseWithError:(nullable NSNumber *)error
                               statusCode:(int32_t)statusCode
                                  headers:(nonnull NSArray *)headers;

@property (nonatomic, readonly, nullable) NSNumber * error;

@property (nonatomic, readonly) int32_t statusCode;

@property (nonatomic, readonly, nonnull) NSArray * headers;

@end
