// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, KHResponseError)
{
    KHResponseErrorCanceled,
    KHResponseErrorTimeout,
    KHResponseErrorNetworkError,
};
