// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import <Foundation/Foundation.h>
@protocol KHHttpClientFactory;


@interface KHRegistry : NSObject

+ (void)setHttpClientFactory:(nonnull id<KHHttpClientFactory>)factory;

@end
