// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import "KHHttpHeader.h"
#import "KHHttpMethod.h"
#import <Foundation/Foundation.h>

@interface KHRequest : NSObject
- (nonnull instancetype)initWithMethod:(KHHttpMethod)method
                                   url:(nonnull NSString *)url
                               headers:(nonnull NSArray<KHHttpHeader *> *)headers;
+ (nonnull instancetype)RequestWithMethod:(KHHttpMethod)method
                                      url:(nonnull NSString *)url
                                  headers:(nonnull NSArray<KHHttpHeader *> *)headers;

@property (nonatomic, readonly) KHHttpMethod method;

@property (nonatomic, readonly, nonnull) NSString * url;

@property (nonatomic, readonly, nonnull) NSArray<KHHttpHeader *> * headers;

@end
