// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import "KHProgressResult.h"
#import <Foundation/Foundation.h>


@interface KHResponseListener : NSObject

/**
 * Returns the progress made on upload and download, measured in bytes. The
 * request can be canceled by returning the appropriate code.
 */
- (KHProgressResult)progress:(int64_t)uploadTransferred
                 uploadTotal:(int64_t)uploadTotal
         downloadTransferred:(int64_t)downloadTransferred
               downloadTotal:(int64_t)downloadTotal;

- (void)dataReceived:(nonnull NSData *)data;

@end
