// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import "KHRequestListener+Private.h"
#import "KHRequestListener.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface KHRequestListener ()

- (id)initWithCpp:(const std::shared_ptr<::Kullo::Http::RequestListener>&)cppRef;

@end

@implementation KHRequestListener {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::Kullo::Http::RequestListener>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::Kullo::Http::RequestListener>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nonnull NSData *)read:(int64_t)maxSize {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->read(::djinni::I64::toCpp(maxSize));
        return ::djinni::Binary::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace ObjCpp { namespace Kullo { namespace Http {

auto RequestListener::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto RequestListener::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<KHRequestListener>(cpp);
}

} } }  // namespace ObjCpp::Kullo::Http

@end
