// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import "KHRequest+Private.h"
#import "DJIMarshal+Private.h"
#import "KHHttpHeader+Private.h"
#include <cassert>

namespace ObjCpp { namespace Kullo { namespace Http {

auto Request::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Enum<::Kullo::Http::HttpMethod, KHHttpMethod>::toCpp(obj.method),
            ::djinni::String::toCpp(obj.url),
            ::djinni::List<::ObjCpp::Kullo::Http::HttpHeader>::toCpp(obj.headers)};
}

auto Request::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[KHRequest alloc] initWithMethod:(::djinni::Enum<::Kullo::Http::HttpMethod, KHHttpMethod>::fromCpp(cpp.method))
                                         url:(::djinni::String::fromCpp(cpp.url))
                                     headers:(::djinni::List<::ObjCpp::Kullo::Http::HttpHeader>::fromCpp(cpp.headers))];
}

} } }  // namespace ObjCpp::Kullo::Http
