// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import "KHRequest.h"
#include "kulloclient/http/Request.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KHRequest;

namespace ObjCpp { namespace Kullo { namespace Http {

struct Request
{
    using CppType = ::Kullo::Http::Request;
    using ObjcType = KHRequest*;

    using Boxed = Request;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} } }  // namespace ObjCpp::Kullo::Http
