// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import "KHResponse.h"


@implementation KHResponse

- (nonnull instancetype)initWithError:(nullable NSNumber *)error
                           statusCode:(int32_t)statusCode
                              headers:(nonnull NSArray *)headers
{
    if (self = [super init]) {
        _error = error;
        _statusCode = statusCode;
        _headers = headers;
    }
    return self;
}

+ (nonnull instancetype)ResponseWithError:(nullable NSNumber *)error
                               statusCode:(int32_t)statusCode
                                  headers:(nonnull NSArray *)headers
{
    return [[self alloc] initWithError:error
                            statusCode:statusCode
                               headers:headers];
}

@end
