// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import "KHProgressResult.h"
#import "KHTransferProgress.h"
#import <Foundation/Foundation.h>


@interface KHResponseListener : NSObject

/**
 * Called when there's progress made on upload or download.
 * The request can be canceled by returning the appropriate code.
 */
- (KHProgressResult)progressed:(nonnull KHTransferProgress *)progress;

- (void)dataReceived:(nonnull NSData *)data;

@end
