// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import "KHResponse+Private.h"
#import "DJIMarshal+Private.h"
#import "KHHttpHeader+Private.h"
#include <cassert>

namespace ObjCpp { namespace Kullo { namespace Http {

auto Response::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Optional<boost::optional, ::djinni::Enum<::Kullo::Http::ResponseError, KHResponseError>>::toCpp(obj.error),
            ::djinni::I32::toCpp(obj.statusCode),
            ::djinni::List<::ObjCpp::Kullo::Http::HttpHeader>::toCpp(obj.headers)};
}

auto Response::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[KHResponse alloc] initWithError:(::djinni::Optional<boost::optional, ::djinni::Enum<::Kullo::Http::ResponseError, KHResponseError>>::fromCpp(cpp.error))
                                  statusCode:(::djinni::I32::fromCpp(cpp.statusCode))
                                     headers:(::djinni::List<::ObjCpp::Kullo::Http::HttpHeader>::fromCpp(cpp.headers))];
}

} } }  // namespace ObjCpp::Kullo::Http
