// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#include "kulloclient/http/RequestListener.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KHRequestListener;

namespace ObjCpp { namespace Kullo { namespace Http {

class RequestListener
{
public:
    using CppType = std::shared_ptr<::Kullo::Http::RequestListener>;
    using ObjcType = KHRequestListener*;

    using Boxed = RequestListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Http

