// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import "KHTransferProgress.h"


@implementation KHTransferProgress

- (nonnull instancetype)initWithUploadTransferred:(int64_t)uploadTransferred
                                      uploadTotal:(int64_t)uploadTotal
                              downloadTransferred:(int64_t)downloadTransferred
                                    downloadTotal:(int64_t)downloadTotal
{
    if (self = [super init]) {
        _uploadTransferred = uploadTransferred;
        _uploadTotal = uploadTotal;
        _downloadTransferred = downloadTransferred;
        _downloadTotal = downloadTotal;
    }
    return self;
}

+ (nonnull instancetype)TransferProgressWithUploadTransferred:(int64_t)uploadTransferred
                                                  uploadTotal:(int64_t)uploadTotal
                                          downloadTransferred:(int64_t)downloadTransferred
                                                downloadTotal:(int64_t)downloadTotal
{
    return [[self alloc] initWithUploadTransferred:uploadTransferred
                                       uploadTotal:uploadTotal
                               downloadTransferred:downloadTransferred
                                     downloadTotal:downloadTotal];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p uploadTransferred:%@ uploadTotal:%@ downloadTransferred:%@ downloadTotal:%@>", self.class, (void *)self, @(self.uploadTransferred), @(self.uploadTotal), @(self.downloadTransferred), @(self.downloadTotal)];
}

@end
