// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import "KHTransferProgress.h"
#include "kulloclient/http/TransferProgress.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KHTransferProgress;

namespace ObjCpp { namespace Kullo { namespace Http {

struct TransferProgress
{
    using CppType = ::Kullo::Http::TransferProgress;
    using ObjcType = KHTransferProgress*;

    using Boxed = TransferProgress;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} } }  // namespace ObjCpp::Kullo::Http
