// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from session.djinni

#import "KAAccountInfo.h"
#include "kulloclient/api/AccountInfo.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KAAccountInfo;

namespace ObjCpp { namespace Kullo { namespace Api {

struct AccountInfo
{
    using CppType = ::Kullo::Api::AccountInfo;
    using ObjcType = KAAccountInfo*;

    using Boxed = AccountInfo;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} } }  // namespace ObjCpp::Kullo::Api
