// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from session.djinni

#import "KAAccountInfo+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace ObjCpp { namespace Kullo { namespace Api {

auto AccountInfo::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Optional<boost::optional, ::djinni::String>::toCpp(obj.planName),
            ::djinni::Optional<boost::optional, ::djinni::I64>::toCpp(obj.storageQuota),
            ::djinni::Optional<boost::optional, ::djinni::I64>::toCpp(obj.storageUsed),
            ::djinni::Optional<boost::optional, ::djinni::String>::toCpp(obj.settingsUrl)};
}

auto AccountInfo::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[KAAccountInfo alloc] initWithPlanName:(::djinni::Optional<boost::optional, ::djinni::String>::fromCpp(cpp.planName))
                                      storageQuota:(::djinni::Optional<boost::optional, ::djinni::I64>::fromCpp(cpp.storageQuota))
                                       storageUsed:(::djinni::Optional<boost::optional, ::djinni::I64>::fromCpp(cpp.storageUsed))
                                       settingsUrl:(::djinni::Optional<boost::optional, ::djinni::String>::fromCpp(cpp.settingsUrl))];
}

} } }  // namespace ObjCpp::Kullo::Api
