// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from session.djinni

#import "KAAccountInfo.h"


@implementation KAAccountInfo

- (nonnull instancetype)initWithSettingsUrl:(nonnull NSString *)settingsUrl
{
    if (self = [super init]) {
        _settingsUrl = [settingsUrl copy];
    }
    return self;
}

+ (nonnull instancetype)AccountInfoWithSettingsUrl:(nonnull NSString *)settingsUrl
{
    return [[self alloc] initWithSettingsUrl:settingsUrl];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p settingsUrl:%@>", self.class, (void *)self, self.settingsUrl];
}

@end
