// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from session.djinni

#import "KAAccountInfo.h"


@implementation KAAccountInfo

- (nonnull instancetype)initWithPlanName:(nullable NSString *)planName
                            storageQuota:(nullable NSNumber *)storageQuota
                             storageUsed:(nullable NSNumber *)storageUsed
                             settingsUrl:(nullable NSString *)settingsUrl
{
    if (self = [super init]) {
        _planName = [planName copy];
        _storageQuota = storageQuota;
        _storageUsed = storageUsed;
        _settingsUrl = [settingsUrl copy];
    }
    return self;
}

+ (nonnull instancetype)AccountInfoWithPlanName:(nullable NSString *)planName
                                   storageQuota:(nullable NSNumber *)storageQuota
                                    storageUsed:(nullable NSNumber *)storageUsed
                                    settingsUrl:(nullable NSString *)settingsUrl
{
    return [[self alloc] initWithPlanName:planName
                             storageQuota:storageQuota
                              storageUsed:storageUsed
                              settingsUrl:settingsUrl];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p planName:%@ storageQuota:%@ storageUsed:%@ settingsUrl:%@>", self.class, (void *)self, self.planName, self.storageQuota, self.storageUsed, self.settingsUrl];
}

@end
