// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "KAAccountInfo+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace ObjCpp { namespace Kullo { namespace Api {

auto AccountInfo::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.settingsUrl)};
}

auto AccountInfo::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[KAAccountInfo alloc] initWithSettingsUrl:(::djinni::String::fromCpp(cpp.settingsUrl))];
}

} } }  // namespace ObjCpp::Kullo::Api
