// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from session.djinni

#import <Foundation/Foundation.h>

/** Information about a Kullo account */
@interface KAAccountInfo : NSObject
- (nonnull instancetype)initWithSettingsUrl:(nonnull NSString *)settingsUrl;
+ (nonnull instancetype)AccountInfoWithSettingsUrl:(nonnull NSString *)settingsUrl;

/**
 * URL to web interface where account settings (notifications, ...) can be
 * configured
 */
@property (nonatomic, readonly, nonnull) NSString * settingsUrl;

@end
