// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "KAAccountInfo.h"


@implementation KAAccountInfo

- (nonnull instancetype)initWithSettingsUrl:(nonnull NSString *)settingsUrl
{
    if (self = [super init]) {
        _settingsUrl = [settingsUrl copy];
    }
    return self;
}

+ (nonnull instancetype)AccountInfoWithSettingsUrl:(nonnull NSString *)settingsUrl
{
    return [[self alloc] initWithSettingsUrl:settingsUrl];
}

@end
