// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from address.djinni

#import "KAAddress.h"
#include "kulloclient/api_impl/Address.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KAAddress;

namespace ObjCpp { namespace Kullo { namespace Api {

struct Address
{
    using CppType = ::Kullo::Api::Address;
    using ObjcType = KAAddress*;

    using Boxed = Address;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} } }  // namespace ObjCpp::Kullo::Api
