// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from address.djinni

#import "KAAddressHelpers+Private.h"
#import "KAAddressHelpers.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "KAAddressBase+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface KAAddressHelpers ()

- (id)initWithCpp:(const std::shared_ptr<::Kullo::Api::AddressHelpers>&)cppRef;

@end

@implementation KAAddressHelpers {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::Kullo::Api::AddressHelpers>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::Kullo::Api::AddressHelpers>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable KAAddress *)create:(nonnull NSString *)address {
    try {
        auto objcpp_result_ = ::Kullo::Api::AddressHelpers::create(::djinni::String::toCpp(address));
        return ::djinni::Optional<boost::optional, ::ObjCpp::Kullo::Api::Address>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace ObjCpp { namespace Kullo { namespace Api {

auto AddressHelpers::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        throw std::invalid_argument("AddressHelpers::toCpp requires non-nil object");
    }
    return kulloForcedNn(objc->_cppRefHandle.get());
}

auto AddressHelpers::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<KAAddressHelpers>(cpp);
}

} } }  // namespace ObjCpp::Kullo::Api

@end
