// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from address.djinni

#include "kulloclient/api/Address.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KAAddress;

namespace ObjCpp { namespace Kullo { namespace Api {

class Address
{
public:
    using CppType = std::shared_ptr<::Kullo::Api::Address>;
    using CppOptType = std::shared_ptr<::Kullo::Api::Address>;
    using ObjcType = KAAddress*;

    using Boxed = Address;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

