// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import <Foundation/Foundation.h>
@class KAAddress;


/** Represents a Kullo address */
@interface KAAddress : NSObject

/**
 * Creates a new Address and converts it to lower case.
 * Returns null if the address is not well-formed.
 */
+ (nullable KAAddress *)create:(nonnull NSString *)address;

/** Returns the whole address */
- (nonnull NSString *)toString;

/** Returns only the part left of the hash symbol */
- (nonnull NSString *)localPart;

/** Returns only the part right of the hash symbol */
- (nonnull NSString *)domainPart;

- (BOOL)isEqualTo:(nullable KAAddress *)other;

/** Returns true iff the left-hand side is alphabetically less than rhs */
- (BOOL)isLessThan:(nullable KAAddress *)rhs;

@end
