// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from address.djinni

#import "KAAddress.h"
#import <Foundation/Foundation.h>


@interface KAAddressHelpers : NSObject

+ (nullable KAAddress *)create:(nonnull NSString *)address;

@end
