// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from address.djinni

#import <Foundation/Foundation.h>
@class KAAddress;

/** Represents a Kullo address */
@interface KAAddressBase : NSObject
- (nonnull instancetype)initWithLocalPart:(nonnull NSString *)localPart
                               domainPart:(nonnull NSString *)domainPart;

/** Constructor must ensure this is normalized */
@property (nonatomic, readonly, nonnull) NSString * localPart;

/** Constructor must ensure this is normalized */
@property (nonatomic, readonly, nonnull) NSString * domainPart;

@end
