// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from address.djinni

#include "kulloclient/api/AddressHelpers.h"
#include <kulloclient/nn.h>
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KAAddressHelpers;

namespace ObjCpp { namespace Kullo { namespace Api {

class AddressHelpers
{
public:
    using CppType = ::Kullo::nn_shared_ptr<::Kullo::Api::AddressHelpers>;
    using CppOptType = std::shared_ptr<::Kullo::Api::AddressHelpers>;
    using ObjcType = KAAddressHelpers*;

    using Boxed = AddressHelpers;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

