// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from address.djinni

#import "KAAddressBase+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace ObjCpp { namespace Kullo { namespace Api {

auto Address::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.localPart),
            ::djinni::String::toCpp(obj.domainPart)};
}

auto Address::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[KAAddress alloc] initWithLocalPart:(::djinni::String::fromCpp(cpp.localPart))
                                     domainPart:(::djinni::String::fromCpp(cpp.domainPart))];
}

} } }  // namespace ObjCpp::Kullo::Api
