// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from asynctask.djinni

#include "kulloclient/api/AsyncTask.h"
#include <kulloclient/nn.h>
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KAAsyncTask;

namespace ObjCpp { namespace Kullo { namespace Api {

class AsyncTask
{
public:
    using CppType = ::Kullo::nn_shared_ptr<::Kullo::Api::AsyncTask>;
    using CppOptType = std::shared_ptr<::Kullo::Api::AsyncTask>;
    using ObjcType = KAAsyncTask*;

    using Boxed = AsyncTask;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

