// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import <Foundation/Foundation.h>


/**
 * Encapsulates an asynchronous task. Must live at least until the task finishes
 * or until it is canceled. If its destructor is called, it will call cancel().
 */
@interface KAAsyncTask : NSObject

/** Cancels the asynchronous task. This will also stop all callbacks. */
- (void)cancel;

/** Returns true iff the task has finished its work. */
- (BOOL)isDone;

/** Blocks until the task has finished executing. */
- (void)waitUntilDone;

/**
 * Blocks until the task has finished executing or until the timeout has
 * expired. Returns false on timeout, true otherwise.
 */
- (BOOL)waitForMs:(int32_t)timeout;

@end
