// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#include "kulloclient/api/AsyncTask.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KAAsyncTask;

namespace ObjCpp { namespace Kullo { namespace Api {

class AsyncTask
{
public:
    using CppType = std::shared_ptr<::Kullo::Api::AsyncTask>;
    using ObjcType = KAAsyncTask*;

    using Boxed = AsyncTask;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

