// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

#import <Foundation/Foundation.h>

/** A block of attachments from a single message */
@interface KAAttachmentsBlockDownloadProgress : NSObject
- (nonnull instancetype)initWithDownloadedBytes:(int64_t)downloadedBytes
                                     totalBytes:(int64_t)totalBytes;
+ (nonnull instancetype)AttachmentsBlockDownloadProgressWithDownloadedBytes:(int64_t)downloadedBytes
                                                                 totalBytes:(int64_t)totalBytes;

@property (nonatomic, readonly) int64_t downloadedBytes;

@property (nonatomic, readonly) int64_t totalBytes;

@end
