// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

#import "KAAttachmentsBlockDownloadProgress+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace ObjCpp { namespace Kullo { namespace Api {

auto AttachmentsBlockDownloadProgress::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I64::toCpp(obj.downloadedBytes),
            ::djinni::I64::toCpp(obj.totalBytes)};
}

auto AttachmentsBlockDownloadProgress::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[KAAttachmentsBlockDownloadProgress alloc] initWithDownloadedBytes:(::djinni::I64::fromCpp(cpp.downloadedBytes))
                                                                    totalBytes:(::djinni::I64::fromCpp(cpp.totalBytes))];
}

} } }  // namespace ObjCpp::Kullo::Api
