// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

#import "KAAttachmentsBlockDownloadProgress.h"
#include "kulloclient/api/AttachmentsBlockDownloadProgress.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KAAttachmentsBlockDownloadProgress;

namespace ObjCpp { namespace Kullo { namespace Api {

struct AttachmentsBlockDownloadProgress
{
    using CppType = ::Kullo::Api::AttachmentsBlockDownloadProgress;
    using ObjcType = KAAttachmentsBlockDownloadProgress*;

    using Boxed = AttachmentsBlockDownloadProgress;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} } }  // namespace ObjCpp::Kullo::Api
