// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

#import "KAAttachmentsBlockDownloadProgress.h"


@implementation KAAttachmentsBlockDownloadProgress

- (nonnull instancetype)initWithDownloadedBytes:(int64_t)downloadedBytes
                                     totalBytes:(int64_t)totalBytes
{
    if (self = [super init]) {
        _downloadedBytes = downloadedBytes;
        _totalBytes = totalBytes;
    }
    return self;
}

+ (nonnull instancetype)AttachmentsBlockDownloadProgressWithDownloadedBytes:(int64_t)downloadedBytes
                                                                 totalBytes:(int64_t)totalBytes
{
    return [[self alloc] initWithDownloadedBytes:downloadedBytes
                                      totalBytes:totalBytes];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p downloadedBytes:%@ totalBytes:%@>", self.class, (void *)self, @(self.downloadedBytes), @(self.totalBytes)];
}

@end
