// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "KAChallenge+Private.h"
#import "KAChallenge.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface KAChallenge ()

- (id)initWithCpp:(const std::shared_ptr<::Kullo::Api::Challenge>&)cppRef;

@end

@implementation KAChallenge {
    ::djinni::DbxCppWrapperCache<::Kullo::Api::Challenge>::Handle _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::Kullo::Api::Challenge>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (KAChallengeType)type {
    try {
        auto r = _cppRefHandle.get()->type();
        return ::djinni::Enum<::Kullo::Api::ChallengeType, KAChallengeType>::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)text {
    try {
        auto r = _cppRefHandle.get()->text();
        return ::djinni::String::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace ObjCpp { namespace Kullo { namespace Api {

auto Challenge::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Challenge::fromCpp(const CppType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::DbxCppWrapperCache<::Kullo::Api::Challenge>::getInstance()->get(cpp, [] (const CppType& p) {
        return [[KAChallenge alloc] initWithCpp:p];
    });
}

} } }  // namespace ObjCpp::Kullo::Api

@end
