// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "KAChallengeType.h"
#import <Foundation/Foundation.h>


@interface KAChallenge : NSObject

- (KAChallengeType)type;

- (nonnull NSString *)text;

@end
