// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from registration.djinni

#include "kulloclient/api/Challenge.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KAChallenge;

namespace ObjCpp { namespace Kullo { namespace Api {

class Challenge
{
public:
    using CppType = std::shared_ptr<::Kullo::Api::Challenge>;
    using CppOptType = std::shared_ptr<::Kullo::Api::Challenge>;
    using ObjcType = KAChallenge*;

    using Boxed = Challenge;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

