// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#import "KAAddress.h"
#import "KALocalError.h"
#import <Foundation/Foundation.h>
@class KASession;


/** Listener used in Client.createSessionAsync() */
@protocol KAClientCreateSessionListener

- (void)migrationStarted:(nonnull KAAddress *)address;

- (void)finished:(nonnull KASession *)session;

- (void)error:(nonnull KAAddress *)address
        error:(KALocalError)error;

@end
