// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#include "kulloclient/api/ClientGenerateKeysListener.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol KAClientGenerateKeysListener;

namespace ObjCpp { namespace Kullo { namespace Api {

class ClientGenerateKeysListener
{
public:
    using CppType = std::shared_ptr<::Kullo::Api::ClientGenerateKeysListener>;
    using ObjcType = id<KAClientGenerateKeysListener>;

    using Boxed = ClientGenerateKeysListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

