// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "KANetworkError.h"
#import <Foundation/Foundation.h>
@class KAAddress;


/** Listener used in Client.addressExistsAsync() */
@protocol KAClientAddressExistsListener

- (void)finished:(nullable KAAddress *)address
          exists:(BOOL)exists;

- (void)error:(nullable KAAddress *)address
        error:(KANetworkError)error;

@end
