// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "KAClient.h"

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"

NSString * __nonnull const KAClientBOTAN = @"Botan";

NSString * __nonnull const KAClientBOOST = @"Boost";

NSString * __nonnull const KAClientJSONCPP = @"JsonCpp";

NSString * __nonnull const KAClientLIBKULLO = @"libkullo";

NSString * __nonnull const KAClientSMARTSQLITE = @"SmartSqlite";

NSString * __nonnull const KAClientSQLITE = @"SQLite";

#pragma clang diagnostic pop
