// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#import "KAAddress.h"
#import "KAMasterKey.h"
#import "KANetworkError.h"
#import <Foundation/Foundation.h>


/** Listener used in Client.checkCredentialsAsync() */
@protocol KAClientCheckCredentialsListener

- (void)finished:(nonnull KAAddress *)address
       masterKey:(nonnull KAMasterKey *)masterKey
           valid:(BOOL)valid;

/**
 * Network errors except NetworkError.Unauthorized, which is handled
 * by finished()
 */
- (void)error:(nonnull KAAddress *)address
        error:(KANetworkError)error;

@end
