// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#import "KAClientGenerateKeysListener+Private.h"
#import "KAClientGenerateKeysListener.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "KARegistration+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace ObjCpp { namespace Kullo { namespace Api {

class ClientGenerateKeysListener::ObjcProxy final
: public ::Kullo::Api::ClientGenerateKeysListener
, public ::djinni::ObjcProxyCache::Handle<ObjcType>
{
public:
    using Handle::Handle;
    void progress(int8_t c_progress) override
    {
        @autoreleasepool {
            [Handle::get() progress:(::djinni::I8::fromCpp(c_progress))];
        }
    }
    void finished(const std::shared_ptr<::Kullo::Api::Registration> & c_registration) override
    {
        @autoreleasepool {
            [Handle::get() finished:(::ObjCpp::Kullo::Api::Registration::fromCpp(c_registration))];
        }
    }
};

} } }  // namespace ObjCpp::Kullo::Api

namespace ObjCpp { namespace Kullo { namespace Api {

auto ClientGenerateKeysListener::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto ClientGenerateKeysListener::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).Handle::get();
}

} } }  // namespace ObjCpp::Kullo::Api
