// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#import "KAClientCreateSessionListener+Private.h"
#import "KAClientCreateSessionListener.h"
#import "DJIObjcWrapperCache+Private.h"
#import "KAAddressBase+Private.h"
#import "KALocalError+Private.h"
#import "KASession+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace ObjCpp { namespace Kullo { namespace Api {

class ClientCreateSessionListener::ObjcProxy final
: public ::Kullo::Api::ClientCreateSessionListener
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::ObjCpp::Kullo::Api::ClientCreateSessionListener;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void migrationStarted(const ::Kullo::Api::Address & c_address) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() migrationStarted:(::ObjCpp::Kullo::Api::Address::fromCpp(c_address))];
        }
    }
    void finished(const ::Kullo::nn_shared_ptr<::Kullo::Api::Session> & c_session) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() finished:(::ObjCpp::Kullo::Api::Session::fromCpp(c_session))];
        }
    }
    void error(const ::Kullo::Api::Address & c_address, ::Kullo::Api::LocalError c_error) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() error:(::ObjCpp::Kullo::Api::Address::fromCpp(c_address))
                                                      error:(::djinni::Enum<::Kullo::Api::LocalError, KALocalError>::fromCpp(c_error))];
        }
    }
};

} } }  // namespace ObjCpp::Kullo::Api

namespace ObjCpp { namespace Kullo { namespace Api {

auto ClientCreateSessionListener::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        throw std::invalid_argument("ClientCreateSessionListener::toCpp requires non-nil object");
    }
    return kulloForcedNn(::djinni::get_objc_proxy<ObjcProxy>(objc));
}

auto ClientCreateSessionListener::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

} } }  // namespace ObjCpp::Kullo::Api
