// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#import "KAClientAddressExistsListener+Private.h"
#import "KAClientAddressExistsListener.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "KAAddressBase+Private.h"
#import "KANetworkError+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace ObjCpp { namespace Kullo { namespace Api {

class ClientAddressExistsListener::ObjcProxy final
: public ::Kullo::Api::ClientAddressExistsListener
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::ObjCpp::Kullo::Api::ClientAddressExistsListener;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void finished(const ::Kullo::Api::Address & c_address, bool c_exists) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() finished:(::ObjCpp::Kullo::Api::Address::fromCpp(c_address))
                                                        exists:(::djinni::Bool::fromCpp(c_exists))];
        }
    }
    void error(const ::Kullo::Api::Address & c_address, ::Kullo::Api::NetworkError c_error) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() error:(::ObjCpp::Kullo::Api::Address::fromCpp(c_address))
                                                      error:(::djinni::Enum<::Kullo::Api::NetworkError, KANetworkError>::fromCpp(c_error))];
        }
    }
};

} } }  // namespace ObjCpp::Kullo::Api

namespace ObjCpp { namespace Kullo { namespace Api {

auto ClientAddressExistsListener::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        throw std::invalid_argument("ClientAddressExistsListener::toCpp requires non-nil object");
    }
    return kulloForcedNn(::djinni::get_objc_proxy<ObjcProxy>(objc));
}

auto ClientAddressExistsListener::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

} } }  // namespace ObjCpp::Kullo::Api
