// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#import "KAClient.h"


NSString * __nonnull const KAClientBOTAN = @"Botan";

NSString * __nonnull const KAClientBOOST = @"Boost";

NSString * __nonnull const KAClientJSONCPP = @"JsonCpp";

NSString * __nonnull const KAClientLIBKULLO = @"libkullo";

NSString * __nonnull const KAClientSMARTSQLITE = @"SmartSqlite";

NSString * __nonnull const KAClientSQLITE = @"SQLite";
