// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "KAClientAddressExistsListener+Private.h"
#import "KAClientAddressExistsListener.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "KAAddress+Private.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace ObjCpp { namespace Kullo { namespace Api {

class ClientAddressExistsListener::ObjcProxy final
: public ::Kullo::Api::ClientAddressExistsListener
, public ::djinni::DbxObjcWrapperCache<ObjcProxy>::Handle
{
public:
    using Handle::Handle;
    void finished(const std::shared_ptr<::Kullo::Api::Address> & c_address, bool c_exists) override
    {
        @autoreleasepool {
            [(ObjcType)Handle::get() finished:(::ObjCpp::Kullo::Api::Address::fromCpp(c_address))
                                       exists:(::djinni::Bool::fromCpp(c_exists))];
        }
    }
    void error(const std::shared_ptr<::Kullo::Api::Address> & c_address, ::Kullo::Api::NetworkError c_error) override
    {
        @autoreleasepool {
            [(ObjcType)Handle::get() error:(::ObjCpp::Kullo::Api::Address::fromCpp(c_address))
                                     error:(::djinni::Enum<::Kullo::Api::NetworkError, KANetworkError>::fromCpp(c_error))];
        }
    }
};

} } }  // namespace ObjCpp::Kullo::Api

namespace ObjCpp { namespace Kullo { namespace Api {

auto ClientAddressExistsListener::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::DbxObjcWrapperCache<ObjcProxy>::getInstance()->get(objc);
}

auto ClientAddressExistsListener::fromCpp(const CppType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).Handle::get();
}

} } }  // namespace ObjCpp::Kullo::Api
