// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#import <Foundation/Foundation.h>
@class KAAddress;
@class KAAsyncTask;
@class KAClient;
@class KAMasterKey;
@protocol KAClientAddressExistsListener;
@protocol KAClientCheckCredentialsListener;
@protocol KAClientCreateSessionListener;
@protocol KAClientGenerateKeysListener;
@protocol KASessionListener;

/** Constants for the use with versions() */
extern NSString * __nonnull const KAClientBOTAN;
extern NSString * __nonnull const KAClientBOOST;
extern NSString * __nonnull const KAClientJSONCPP;
extern NSString * __nonnull const KAClientLIBKULLO;
extern NSString * __nonnull const KAClientSMARTSQLITE;
extern NSString * __nonnull const KAClientSQLITE;

/** A Client is the entry point to most of libkullo. */
@interface KAClient : NSObject

/** Create a new Client instance. You will most probably only need one. */
+ (nullable KAClient *)create;

/**
 * Opens a session for the given user. dbFilePath is the absolute path to the
 * database file, including the filename. The folder must exist, and it must
 * be possible for the current user to create files in it. The file itself is
 * created if it doesn't already exist.
 *
 * Attention: Don't ever re-use the same DB file for multiple accounts!
 */
- (nullable KAAsyncTask *)createSessionAsync:(nullable KAAddress *)address
                                   masterKey:(nullable KAMasterKey *)masterKey
                                  dbFilePath:(nonnull NSString *)dbFilePath
                             sessionListener:(nullable id<KASessionListener>)sessionListener
                                    listener:(nullable id<KAClientCreateSessionListener>)listener;

/** Check whether an address exists. */
- (nullable KAAsyncTask *)addressExistsAsync:(nullable KAAddress *)address
                                    listener:(nullable id<KAClientAddressExistsListener>)listener;

/** Check whether the master key is valid for the given address. */
- (nullable KAAsyncTask *)checkCredentialsAsync:(nullable KAAddress *)address
                                      masterKey:(nullable KAMasterKey *)masterKey
                                       listener:(nullable id<KAClientCheckCredentialsListener>)listener;

/** Generate new keys, which is the first step to registering an account. */
- (nullable KAAsyncTask *)generateKeysAsync:(nullable id<KAClientGenerateKeysListener>)listener;

/** Returns pairs of <library name, version number> for the libraries used. */
- (nonnull NSDictionary<NSString *, NSString *> *)versions;

@end
