// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#include "kulloclient/api/ClientCheckLoginListener.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol KAClientCheckLoginListener;

namespace ObjCpp { namespace Kullo { namespace Api {

class ClientCheckLoginListener
{
public:
    using CppType = std::shared_ptr<::Kullo::Api::ClientCheckLoginListener>;
    using ObjcType = id<KAClientCheckLoginListener>;

    using Boxed = ClientCheckLoginListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

