// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#import "KALocalError.h"
#import <Foundation/Foundation.h>
@class KAAddress;
@class KASession;


/** Listener used in Client.createSessionAsync() */
@protocol KAClientCreateSessionListener

- (void)migrationStarted:(nullable KAAddress *)address;

- (void)finished:(nullable KASession *)session;

- (void)error:(nullable KAAddress *)address
        error:(KALocalError)error;

@end
