// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "KANetworkError.h"
#import <Foundation/Foundation.h>
@class KAAddress;
@class KAMasterKey;


/** Listener used in Client.checkCredentialsAsync() */
@protocol KAClientCheckCredentialsListener

- (void)finished:(nullable KAAddress *)address
       masterKey:(nullable KAMasterKey *)masterKey
           valid:(BOOL)valid;

- (void)error:(nullable KAAddress *)address
        error:(KANetworkError)error;

@end
