// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from conversations.djinni

#include "kulloclient/api/Conversations.h"
#include <kulloclient/nn.h>
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KAConversations;

namespace ObjCpp { namespace Kullo { namespace Api {

class Conversations
{
public:
    using CppType = ::Kullo::nn_shared_ptr<::Kullo::Api::Conversations>;
    using CppOptType = std::shared_ptr<::Kullo::Api::Conversations>;
    using ObjcType = KAConversations*;

    using Boxed = Conversations;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

