// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#include "kulloclient/api/Conversations.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KAConversations;

namespace ObjCpp { namespace Kullo { namespace Api {

class Conversations
{
public:
    using CppType = std::shared_ptr<::Kullo::Api::Conversations>;
    using ObjcType = KAConversations*;

    using Boxed = Conversations;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

