// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "KAConversations+Private.h"
#import "KAConversations.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "KAAddress+Private.h"
#import "KADateTimeBase+Private.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface KAConversations ()

- (id)initWithCpp:(const std::shared_ptr<::Kullo::Api::Conversations>&)cppRef;

@end

@implementation KAConversations {
    ::djinni::DbxCppWrapperCache<::Kullo::Api::Conversations>::Handle _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::Kullo::Api::Conversations>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nonnull NSArray *)all {
    try {
        auto r = _cppRefHandle.get()->all();
        return ::djinni::List<::djinni::I64>::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (int64_t)get:(nonnull NSSet *)participants {
    try {
        auto r = _cppRefHandle.get()->get(::djinni::Set<::ObjCpp::Kullo::Api::Address>::toCpp(participants));
        return ::djinni::I64::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (int64_t)add:(nonnull NSSet *)participants {
    try {
        auto r = _cppRefHandle.get()->add(::djinni::Set<::ObjCpp::Kullo::Api::Address>::toCpp(participants));
        return ::djinni::I64::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)remove:(int64_t)convId {
    try {
        _cppRefHandle.get()->remove(::djinni::I64::toCpp(convId));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSSet *)participants:(int64_t)convId {
    try {
        auto r = _cppRefHandle.get()->participants(::djinni::I64::toCpp(convId));
        return ::djinni::Set<::ObjCpp::Kullo::Api::Address>::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (int32_t)totalMessages:(int64_t)convId {
    try {
        auto r = _cppRefHandle.get()->totalMessages(::djinni::I64::toCpp(convId));
        return ::djinni::I32::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (int32_t)unreadMessages:(int64_t)convId {
    try {
        auto r = _cppRefHandle.get()->unreadMessages(::djinni::I64::toCpp(convId));
        return ::djinni::I32::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (int32_t)undoneMessages:(int64_t)convId {
    try {
        auto r = _cppRefHandle.get()->undoneMessages(::djinni::I64::toCpp(convId));
        return ::djinni::I32::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull KADateTime *)latestMessageTimestamp:(int64_t)convId {
    try {
        auto r = _cppRefHandle.get()->latestMessageTimestamp(::djinni::I64::toCpp(convId));
        return ::ObjCpp::Kullo::Api::DateTime::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nonnull KADateTime *)emptyConversationTimestamp {
    try {
        auto r = ::Kullo::Api::Conversations::emptyConversationTimestamp();
        return ::ObjCpp::Kullo::Api::DateTime::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace ObjCpp { namespace Kullo { namespace Api {

auto Conversations::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Conversations::fromCpp(const CppType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::DbxCppWrapperCache<::Kullo::Api::Conversations>::getInstance()->get(cpp, [] (const CppType& p) {
        return [[KAConversations alloc] initWithCpp:p];
    });
}

} } }  // namespace ObjCpp::Kullo::Api

@end
