// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import <Foundation/Foundation.h>
@class KADateTime;

@interface KADateTimeBase : NSObject
- (nonnull instancetype)initWithYear:(int16_t)year
                               month:(int8_t)month
                                 day:(int8_t)day
                                hour:(int8_t)hour
                              minute:(int8_t)minute
                              second:(int8_t)second
                     tzOffsetMinutes:(int16_t)tzOffsetMinutes;

@property (nonatomic, readonly) int16_t year;

@property (nonatomic, readonly) int8_t month;

@property (nonatomic, readonly) int8_t day;

@property (nonatomic, readonly) int8_t hour;

@property (nonatomic, readonly) int8_t minute;

@property (nonatomic, readonly) int8_t second;

@property (nonatomic, readonly) int16_t tzOffsetMinutes;

@end
