// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from datetime.djinni

#import "KADateTimeBase+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace ObjCpp { namespace Kullo { namespace Api {

auto DateTime::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I16::toCpp(obj.year),
            ::djinni::I8::toCpp(obj.month),
            ::djinni::I8::toCpp(obj.day),
            ::djinni::I8::toCpp(obj.hour),
            ::djinni::I8::toCpp(obj.minute),
            ::djinni::I8::toCpp(obj.second),
            ::djinni::I16::toCpp(obj.tzOffsetMinutes)};
}

auto DateTime::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[KADateTime alloc] initWithYear:(::djinni::I16::fromCpp(cpp.year))
                                      month:(::djinni::I8::fromCpp(cpp.month))
                                        day:(::djinni::I8::fromCpp(cpp.day))
                                       hour:(::djinni::I8::fromCpp(cpp.hour))
                                     minute:(::djinni::I8::fromCpp(cpp.minute))
                                     second:(::djinni::I8::fromCpp(cpp.second))
                            tzOffsetMinutes:(::djinni::I16::fromCpp(cpp.tzOffsetMinutes))];
}

} } }  // namespace ObjCpp::Kullo::Api
