// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from datetime.djinni

#import "KADateTime.h"


@implementation KADateTimeBase

- (nonnull instancetype)initWithYear:(int16_t)year
                               month:(int8_t)month
                                 day:(int8_t)day
                                hour:(int8_t)hour
                              minute:(int8_t)minute
                              second:(int8_t)second
                     tzOffsetMinutes:(int16_t)tzOffsetMinutes
{
    if (self = [super init]) {
        _year = year;
        _month = month;
        _day = day;
        _hour = hour;
        _minute = minute;
        _second = second;
        _tzOffsetMinutes = tzOffsetMinutes;
    }
    return self;
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p year:%@ month:%@ day:%@ hour:%@ minute:%@ second:%@ tzOffsetMinutes:%@>", self.class, self, @(self.year), @(self.month), @(self.day), @(self.hour), @(self.minute), @(self.second), @(self.tzOffsetMinutes)];
}

@end
