// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import "KADelivery+Private.h"
#import "KADelivery.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "KAAddressBase+Private.h"
#import "KADateTimeBase+Private.h"
#import "KADeliveryReason+Private.h"
#import "KADeliveryState+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface KADelivery ()

- (id)initWithCpp:(const std::shared_ptr<::Kullo::Api::Delivery>&)cppRef;

@end

@implementation KADelivery {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::Kullo::Api::Delivery>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::Kullo::Api::Delivery>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nonnull KAAddress *)recipient {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->recipient();
        return ::ObjCpp::Kullo::Api::Address::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (KADeliveryState)state {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->state();
        return ::djinni::Enum<::Kullo::Api::DeliveryState, KADeliveryState>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable NSNumber *)reason {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->reason();
        return ::djinni::Optional<boost::optional, ::djinni::Enum<::Kullo::Api::DeliveryReason, KADeliveryReason>>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable KADateTime *)date {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->date();
        return ::djinni::Optional<boost::optional, ::ObjCpp::Kullo::Api::DateTime>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace ObjCpp { namespace Kullo { namespace Api {

auto Delivery::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        throw std::invalid_argument("Delivery::toCpp requires non-nil object");
    }
    return kulloForcedNn(objc->_cppRefHandle.get());
}

auto Delivery::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<KADelivery>(cpp);
}

} } }  // namespace ObjCpp::Kullo::Api

@end
