// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, KADeliveryState)
{
    KADeliveryStateUnsent,
    KADeliveryStateDelivered,
    KADeliveryStateFailed,
};
