// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#include "kulloclient/api/Delivery.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KADelivery;

namespace ObjCpp { namespace Kullo { namespace Api {

class Delivery
{
public:
    using CppType = std::shared_ptr<::Kullo::Api::Delivery>;
    using CppOptType = std::shared_ptr<::Kullo::Api::Delivery>;
    using ObjcType = KADelivery*;

    using Boxed = Delivery;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

