// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from drafts.djinni

#include "kulloclient/api/DraftAttachmentsAddListener.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol KADraftAttachmentsAddListener;

namespace ObjCpp { namespace Kullo { namespace Api {

class DraftAttachmentsAddListener
{
public:
    using CppType = std::shared_ptr<::Kullo::Api::DraftAttachmentsAddListener>;
    using CppOptType = std::shared_ptr<::Kullo::Api::DraftAttachmentsAddListener>;
    using ObjcType = id<KADraftAttachmentsAddListener>;

    using Boxed = DraftAttachmentsAddListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

