// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from drafts.djinni

#import <Foundation/Foundation.h>
@class KAAsyncTask;
@protocol KADraftAttachmentsAddListener;
@protocol KADraftAttachmentsContentListener;
@protocol KADraftAttachmentsSaveToListener;


@interface KADraftAttachments : NSObject

/** Returns all attachments for the given draft */
- (nonnull NSArray<NSNumber *> *)allForDraft:(int64_t)convId;

/** Adds a new attachment to a draft */
- (nullable KAAsyncTask *)addAsync:(int64_t)convId
                              path:(nonnull NSString *)path
                          mimeType:(nonnull NSString *)mimeType
                          listener:(nullable id<KADraftAttachmentsAddListener>)listener;

/** Removes an attachment from a draft */
- (void)remove:(int64_t)convId
         attId:(int64_t)attId;

- (nonnull NSString *)filename:(int64_t)convId
                         attId:(int64_t)attId;

- (void)setFilename:(int64_t)convId
              attId:(int64_t)attId
           filename:(nonnull NSString *)filename;

- (nonnull NSString *)mimeType:(int64_t)convId
                         attId:(int64_t)attId;

- (int64_t)size:(int64_t)convId
          attId:(int64_t)attId;

- (nonnull NSString *)hash:(int64_t)convId
                     attId:(int64_t)attId;

/** Gets the content of the attachment as a BLOB */
- (nullable KAAsyncTask *)contentAsync:(int64_t)convId
                                 attId:(int64_t)attId
                              listener:(nullable id<KADraftAttachmentsContentListener>)listener;

/**
 * Saves the content of the attachment to a file. Path contains the absolute
 * path where the file should be saved, including the filename.
 */
- (nullable KAAsyncTask *)saveToAsync:(int64_t)convId
                                attId:(int64_t)attId
                                 path:(nonnull NSString *)path
                             listener:(nullable id<KADraftAttachmentsSaveToListener>)listener;

@end
