// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from drafts.djinni

#include "kulloclient/api/DraftAttachments.h"
#include <kulloclient/nn.h>
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KADraftAttachments;

namespace ObjCpp { namespace Kullo { namespace Api {

class DraftAttachments
{
public:
    using CppType = ::Kullo::nn_shared_ptr<::Kullo::Api::DraftAttachments>;
    using CppOptType = std::shared_ptr<::Kullo::Api::DraftAttachments>;
    using ObjcType = KADraftAttachments*;

    using Boxed = DraftAttachments;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

