// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from drafts.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, KADraftState)
{
    KADraftStateEditing,
    KADraftStateSending,
};
