// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from drafts.djinni

#import "KADraftAttachmentsAddListener+Private.h"
#import "KADraftAttachmentsAddListener.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "KALocalError+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace ObjCpp { namespace Kullo { namespace Api {

class DraftAttachmentsAddListener::ObjcProxy final
: public ::Kullo::Api::DraftAttachmentsAddListener
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::ObjCpp::Kullo::Api::DraftAttachmentsAddListener;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void progressed(int64_t c_convId, int64_t c_attId, int64_t c_bytesProcessed, int64_t c_bytesTotal) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() progressed:(::djinni::I64::fromCpp(c_convId))
                                                           attId:(::djinni::I64::fromCpp(c_attId))
                                                  bytesProcessed:(::djinni::I64::fromCpp(c_bytesProcessed))
                                                      bytesTotal:(::djinni::I64::fromCpp(c_bytesTotal))];
        }
    }
    void finished(int64_t c_convId, int64_t c_attId, const std::string & c_path) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() finished:(::djinni::I64::fromCpp(c_convId))
                                                         attId:(::djinni::I64::fromCpp(c_attId))
                                                          path:(::djinni::String::fromCpp(c_path))];
        }
    }
    void error(int64_t c_convId, const std::string & c_path, ::Kullo::Api::LocalError c_error) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() error:(::djinni::I64::fromCpp(c_convId))
                                                       path:(::djinni::String::fromCpp(c_path))
                                                      error:(::djinni::Enum<::Kullo::Api::LocalError, KALocalError>::fromCpp(c_error))];
        }
    }
};

} } }  // namespace ObjCpp::Kullo::Api

namespace ObjCpp { namespace Kullo { namespace Api {

auto DraftAttachmentsAddListener::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto DraftAttachmentsAddListener::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

} } }  // namespace ObjCpp::Kullo::Api
