// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from drafts.djinni

#import "KADraftState.h"
#import <Foundation/Foundation.h>


@interface KADrafts : NSObject

- (nonnull NSString *)text:(int64_t)convId;

- (void)setText:(int64_t)convId
           text:(nonnull NSString *)text;

- (KADraftState)state:(int64_t)convId;

/**
 * The draft will be sent on the next sync. This will throw an exception if
 * UserSettings::name() is empty.
 */
- (void)prepareToSend:(int64_t)convId;

/** Clears the draft and removes the corresponding attachments. */
- (void)clear:(int64_t)convId;

@end
