// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "KALocalError.h"
#import <Foundation/Foundation.h>


/** Listener used in DraftAttachments.saveToAsync() */
@protocol KADraftAttachmentsSaveToListener

- (void)finished:(int64_t)convId
           attId:(int64_t)attId
            path:(nonnull NSString *)path;

- (void)error:(int64_t)convId
        attId:(int64_t)attId
         path:(nonnull NSString *)path
        error:(KALocalError)error;

@end
