// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from drafts.djinni

#import "KADraftAttachmentsContentListener+Private.h"
#import "KADraftAttachmentsContentListener.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace ObjCpp { namespace Kullo { namespace Api {

class DraftAttachmentsContentListener::ObjcProxy final
: public ::Kullo::Api::DraftAttachmentsContentListener
, public ::djinni::ObjcProxyCache::Handle<ObjcType>
{
public:
    using Handle::Handle;
    void finished(int64_t c_convId, int64_t c_attId, const std::vector<uint8_t> & c_content) override
    {
        @autoreleasepool {
            [Handle::get() finished:(::djinni::I64::fromCpp(c_convId))
                              attId:(::djinni::I64::fromCpp(c_attId))
                            content:(::djinni::Binary::fromCpp(c_content))];
        }
    }
};

} } }  // namespace ObjCpp::Kullo::Api

namespace ObjCpp { namespace Kullo { namespace Api {

auto DraftAttachmentsContentListener::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto DraftAttachmentsContentListener::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).Handle::get();
}

} } }  // namespace ObjCpp::Kullo::Api
