// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from drafts.djinni

#import "KALocalError.h"
#import <Foundation/Foundation.h>


/** Listener used in DraftAttachments.addAsync() */
@protocol KADraftAttachmentsAddListener

/**
 * Indicates progress when adding an attachment.
 * Note: not guaranteed to be called at any specific point.
 */
- (void)progressed:(int64_t)convId
             attId:(int64_t)attId
    bytesProcessed:(int64_t)bytesProcessed
        bytesTotal:(int64_t)bytesTotal;

- (void)finished:(int64_t)convId
           attId:(int64_t)attId
            path:(nonnull NSString *)path;

- (void)error:(int64_t)convId
         path:(nonnull NSString *)path
        error:(KALocalError)error;

@end
