// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, KADraftPart)
{
    KADraftPartContent,
    KADraftPartAttachments,
};
