// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from session.djinni

#import "KAEvent.h"


@implementation KAEvent

- (nonnull instancetype)initWithEvent:(KAEventType)event
                       conversationId:(int64_t)conversationId
                            messageId:(int64_t)messageId
                         attachmentId:(int64_t)attachmentId
{
    if (self = [super init]) {
        _event = event;
        _conversationId = conversationId;
        _messageId = messageId;
        _attachmentId = attachmentId;
    }
    return self;
}

+ (nonnull instancetype)EventWithEvent:(KAEventType)event
                        conversationId:(int64_t)conversationId
                             messageId:(int64_t)messageId
                          attachmentId:(int64_t)attachmentId
{
    return [[self alloc] initWithEvent:event
                        conversationId:conversationId
                             messageId:messageId
                          attachmentId:attachmentId];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p event:%@ conversationId:%@ messageId:%@ attachmentId:%@>", self.class, self, @(self.event), @(self.conversationId), @(self.messageId), @(self.attachmentId)];
}

@end
