// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from session.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, KAEventType)
{
    KAEventTypeConversationAdded,
    KAEventTypeConversationChanged,
    KAEventTypeConversationRemoved,
    KAEventTypeDraftStateChanged,
    KAEventTypeDraftTextChanged,
    KAEventTypeDraftAttachmentAdded,
    KAEventTypeDraftAttachmentRemoved,
    KAEventTypeMessageAdded,
    KAEventTypeMessageDeliveryChanged,
    KAEventTypeMessageStateChanged,
    KAEventTypeMessageAttachmentsDownloadedChanged,
    KAEventTypeMessageRemoved,
    KAEventTypeLatestSenderChanged,
};
