// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from event.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, KAEventType)
{
    /** Conversation added */
    KAEventTypeConversationAdded,
    /** Conversation removed */
    KAEventTypeConversationRemoved,
    /** Any property of Conversations has changed for a single conversation */
    KAEventTypeConversationChanged,
    /**
     * Timestamp of the latest message in a single conversation changed. This may affect
     * the order of the conversations list. Whenever this is emitted, ConversationChanged
     * is also emitted.
     */
    KAEventTypeConversationLatestMessageTimestampChanged,
    KAEventTypeDraftStateChanged,
    KAEventTypeDraftTextChanged,
    KAEventTypeDraftAttachmentAdded,
    KAEventTypeDraftAttachmentRemoved,
    KAEventTypeMessageAdded,
    KAEventTypeMessageDeliveryChanged,
    KAEventTypeMessageStateChanged,
    KAEventTypeMessageAttachmentsDownloadedChanged,
    KAEventTypeMessageRemoved,
    /**
     * One of the user settings keys changed. Emitted once for every key that changed.
     * TODO: pass key with this event
     */
    KAEventTypeUserSettingsChanged,
};
