// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "KAEvent.h"
#include "kulloclient/api/Event.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KAEvent;

namespace ObjCpp { namespace Kullo { namespace Api {

struct Event
{
    using CppType = ::Kullo::Api::Event;
    using ObjcType = KAEvent*;

    using Boxed = Event;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} } }  // namespace ObjCpp::Kullo::Api
