// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from address.djinni

#import <Foundation/Foundation.h>


@interface KAInternalAddressUtils : NSObject

/** Checks a set of Address constructor arguments for validity */
+ (BOOL)isValid:(nonnull NSString *)localPart
     domainPart:(nonnull NSString *)domainPart;

@end
