// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from masterkey.djinni

#import <Foundation/Foundation.h>


@interface KAInternalMasterKeyUtils : NSObject

/** Checks a MasterKey constructor argument for validity */
+ (BOOL)isValid:(nonnull NSArray<NSString *> *)blocks;

@end
