// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from session.djinni

#import <Foundation/Foundation.h>


/**
 * Intentionally empty interface, because it cannot be used outside of C++,
 * other than being passed along to Session.notify().
 */
@interface KAInternalEvent : NSObject

@end
