// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#include "kulloclient/api/InternalEvent.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KAInternalEvent;

namespace ObjCpp { namespace Kullo { namespace Api {

class InternalEvent
{
public:
    using CppType = std::shared_ptr<::Kullo::Api::InternalEvent>;
    using ObjcType = KAInternalEvent*;

    using Boxed = InternalEvent;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

