// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "KALogType.h"
#import <Foundation/Foundation.h>


/** Listener used in Registry.setLogListener() */
@protocol KALogListener

/** Called whenever libkullo produces a log message. */
- (void)writeLogMessage:(nonnull NSString *)file
                   line:(int32_t)line
               function:(nonnull NSString *)function
                   type:(KALogType)type
                message:(nonnull NSString *)message
                 thread:(nonnull NSString *)thread
             stacktrace:(nonnull NSString *)stacktrace;

@end
