// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#include "kulloclient/api/LogListener.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol KALogListener;

namespace ObjCpp { namespace Kullo { namespace Api {

class LogListener
{
public:
    using CppType = std::shared_ptr<::Kullo::Api::LogListener>;
    using ObjcType = id<KALogListener>;

    using Boxed = LogListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

