// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from log.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, KALogType)
{
    KALogTypeNone,
    KALogTypeDebug,
    KALogTypeInfo,
    KALogTypeWarning,
    KALogTypeError,
    KALogTypeFatal,
};
