// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, KALocalError)
{
    /** Couldn't read or write to file */
    KALocalErrorFilesystem,
    /** Any other error */
    KALocalErrorUnknown,
};
