// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from masterkey.djinni

#import <Foundation/Foundation.h>
@class KAMasterKey;

@interface KAMasterKeyBase : NSObject
- (nonnull instancetype)initWithBlocks:(nonnull NSArray<NSString *> *)blocks;

/** key as 16 blocks of 6 digits each */
@property (nonatomic, readonly, nonnull) NSArray<NSString *> * blocks;

@end
