// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from masterkey.djinni

#import "KAMasterKey.h"
#import <Foundation/Foundation.h>


@interface KAMasterKeyHelpers : NSObject

/** Returns null if pem is not well-formed */
+ (nullable KAMasterKey *)createFromPem:(nonnull NSString *)pem;

/** Returns null if dataBlocks is not well-formed */
+ (nullable KAMasterKey *)createFromDataBlocks:(nonnull NSArray<NSString *> *)dataBlocks;

/**
 * Validates a single block.
 * A block string is valid iff it contains exactly 6 digits
 * and fulfills the Luhn mod10 requirements
 */
+ (BOOL)isValidBlock:(nonnull NSString *)block;

/** Returns PEM formatted MasterKey */
+ (nonnull NSString *)toPem:(nonnull KAMasterKey *)masterKey;

/**
 * Returns the MasterKey, encrypted with the given password.
 * Shouldn't be called from the UI thread as it is (deliberately) slow.
 */
+ (nonnull NSString *)encrypt:(nonnull NSString *)password
                    masterKey:(nonnull KAMasterKey *)masterKey;

/**
 * Decrypted an encrypted MasterKey, given a password.
 * Shouldn't be called from the UI thread as it is (deliberately) slow.
 * Returns null if given the wrong password.
 */
+ (nullable KAMasterKey *)decrypt:(nonnull NSString *)password
               encryptedMasterKey:(nonnull NSString *)encryptedMasterKey;

@end
