// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "KAMasterKey+Private.h"
#import "KAMasterKey.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "KAMasterKey+Private.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface KAMasterKey ()

- (id)initWithCpp:(const std::shared_ptr<::Kullo::Api::MasterKey>&)cppRef;

@end

@implementation KAMasterKey {
    ::djinni::DbxCppWrapperCache<::Kullo::Api::MasterKey>::Handle _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::Kullo::Api::MasterKey>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable KAMasterKey *)createFromPem:(nonnull NSString *)pem {
    try {
        auto r = ::Kullo::Api::MasterKey::createFromPem(::djinni::String::toCpp(pem));
        return ::ObjCpp::Kullo::Api::MasterKey::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable KAMasterKey *)createFromDataBlocks:(nonnull NSArray *)dataBlocks {
    try {
        auto r = ::Kullo::Api::MasterKey::createFromDataBlocks(::djinni::List<::djinni::String>::toCpp(dataBlocks));
        return ::ObjCpp::Kullo::Api::MasterKey::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (BOOL)isValidBlock:(nonnull NSString *)block {
    try {
        auto r = ::Kullo::Api::MasterKey::isValidBlock(::djinni::String::toCpp(block));
        return ::djinni::Bool::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)pem {
    try {
        auto r = _cppRefHandle.get()->pem();
        return ::djinni::String::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSArray *)dataBlocks {
    try {
        auto r = _cppRefHandle.get()->dataBlocks();
        return ::djinni::List<::djinni::String>::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (BOOL)isEqualTo:(nullable KAMasterKey *)other {
    try {
        auto r = _cppRefHandle.get()->isEqualTo(::ObjCpp::Kullo::Api::MasterKey::toCpp(other));
        return ::djinni::Bool::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace ObjCpp { namespace Kullo { namespace Api {

auto MasterKey::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto MasterKey::fromCpp(const CppType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::DbxCppWrapperCache<::Kullo::Api::MasterKey>::getInstance()->get(cpp, [] (const CppType& p) {
        return [[KAMasterKey alloc] initWithCpp:p];
    });
}

} } }  // namespace ObjCpp::Kullo::Api

@end
