// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import <Foundation/Foundation.h>
@class KAMasterKey;


@interface KAMasterKey : NSObject

/** Returns null if pem is not well-formed */
+ (nullable KAMasterKey *)createFromPem:(nonnull NSString *)pem;

/** Returns null if dataBlocks is not well-formed */
+ (nullable KAMasterKey *)createFromDataBlocks:(nonnull NSArray *)dataBlocks;

/**
 * Validates a single block.
 * A block string is valid iff it contains exactly 6 digits
 * and fulfills the Luhn mod10 requirements
 */
+ (BOOL)isValidBlock:(nonnull NSString *)block;

/** Returns PEM formatted key */
- (nonnull NSString *)pem;

/** Returns the key as 16 blocks of 6 digits each */
- (nonnull NSArray *)dataBlocks;

- (BOOL)isEqualTo:(nullable KAMasterKey *)other;

@end
