// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from masterkey.djinni

#import "KAMasterKeyBase+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace ObjCpp { namespace Kullo { namespace Api {

auto MasterKey::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::List<::djinni::String>::toCpp(obj.blocks)};
}

auto MasterKey::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[KAMasterKey alloc] initWithBlocks:(::djinni::List<::djinni::String>::fromCpp(cpp.blocks))];
}

} } }  // namespace ObjCpp::Kullo::Api
