// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from masterkey.djinni

#include "kulloclient/api/MasterKeyHelpers.h"
#include <kulloclient/nn.h>
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KAMasterKeyHelpers;

namespace ObjCpp { namespace Kullo { namespace Api {

class MasterKeyHelpers
{
public:
    using CppType = ::Kullo::nn_shared_ptr<::Kullo::Api::MasterKeyHelpers>;
    using CppOptType = std::shared_ptr<::Kullo::Api::MasterKeyHelpers>;
    using ObjcType = KAMasterKeyHelpers*;

    using Boxed = MasterKeyHelpers;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

