// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from masterkey.djinni

#include "kulloclient/api/MasterKey.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KAMasterKey;

namespace ObjCpp { namespace Kullo { namespace Api {

class MasterKey
{
public:
    using CppType = std::shared_ptr<::Kullo::Api::MasterKey>;
    using CppOptType = std::shared_ptr<::Kullo::Api::MasterKey>;
    using ObjcType = KAMasterKey*;

    using Boxed = MasterKey;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

