// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from masterkey.djinni

#import "KAMasterKey.h"
#include "kulloclient/api_impl/MasterKey.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KAMasterKey;

namespace ObjCpp { namespace Kullo { namespace Api {

struct MasterKey
{
    using CppType = ::Kullo::Api::MasterKey;
    using ObjcType = KAMasterKey*;

    using Boxed = MasterKey;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} } }  // namespace ObjCpp::Kullo::Api
