// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from masterkey.djinni

#import "KAMasterKey.h"


@implementation KAMasterKeyBase

- (nonnull instancetype)initWithBlocks:(nonnull NSArray<NSString *> *)blocks
{
    if (self = [super init]) {
        _blocks = [blocks copy];
    }
    return self;
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p blocks:%@>", self.class, (void *)self, self.blocks];
}

@end
