// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import "KADateTime.h"
#import <Foundation/Foundation.h>

@interface KAMessagesSearchResult : NSObject
- (nonnull instancetype)initWithMsgId:(int64_t)msgId
                               convId:(int64_t)convId
                        senderAddress:(nonnull NSString *)senderAddress
                         dateReceived:(nonnull KADateTime *)dateReceived
                              snippet:(nonnull NSString *)snippet
                             boundary:(nonnull NSString *)boundary;
+ (nonnull instancetype)MessagesSearchResultWithMsgId:(int64_t)msgId
                                               convId:(int64_t)convId
                                        senderAddress:(nonnull NSString *)senderAddress
                                         dateReceived:(nonnull KADateTime *)dateReceived
                                              snippet:(nonnull NSString *)snippet
                                             boundary:(nonnull NSString *)boundary;

@property (nonatomic, readonly) int64_t msgId;

@property (nonatomic, readonly) int64_t convId;

@property (nonatomic, readonly, nonnull) NSString * senderAddress;

@property (nonatomic, readonly, nonnull) KADateTime * dateReceived;

/**
 * Snippet contains search strings wrapped in "(XYZ)" and "(/XYZ)" where XYZ
 * is a random boundary in the format [a-zA-Z0-9]+ generated in every search
 */
@property (nonatomic, readonly, nonnull) NSString * snippet;

@property (nonatomic, readonly, nonnull) NSString * boundary;

@end
