// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#include "kulloclient/api/MessagesSearchListener.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol KAMessagesSearchListener;

namespace ObjCpp { namespace Kullo { namespace Api {

class MessagesSearchListener
{
public:
    using CppType = std::shared_ptr<::Kullo::Api::MessagesSearchListener>;
    using CppOptType = std::shared_ptr<::Kullo::Api::MessagesSearchListener>;
    using ObjcType = id<KAMessagesSearchListener>;

    using Boxed = MessagesSearchListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

