// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import "KAMessagesSearchResult.h"
#import <Foundation/Foundation.h>


@protocol KAMessagesSearchListener

- (void)finished:(nonnull NSArray<KAMessagesSearchResult *> *)results;

@end
