// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import "KAMessagesSearchResult.h"
#include "kulloclient/api/MessagesSearchResult.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KAMessagesSearchResult;

namespace ObjCpp { namespace Kullo { namespace Api {

struct MessagesSearchResult
{
    using CppType = ::Kullo::Api::MessagesSearchResult;
    using ObjcType = KAMessagesSearchResult*;

    using Boxed = MessagesSearchResult;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} } }  // namespace ObjCpp::Kullo::Api
