// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import "KAMessagesSearchResult+Private.h"
#import "DJIMarshal+Private.h"
#import "KADateTimeBase+Private.h"
#include <cassert>

namespace ObjCpp { namespace Kullo { namespace Api {

auto MessagesSearchResult::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I64::toCpp(obj.msgId),
            ::djinni::I64::toCpp(obj.convId),
            ::djinni::String::toCpp(obj.senderAddress),
            ::ObjCpp::Kullo::Api::DateTime::toCpp(obj.dateReceived),
            ::djinni::String::toCpp(obj.snippet),
            ::djinni::String::toCpp(obj.boundary)};
}

auto MessagesSearchResult::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[KAMessagesSearchResult alloc] initWithMsgId:(::djinni::I64::fromCpp(cpp.msgId))
                                                  convId:(::djinni::I64::fromCpp(cpp.convId))
                                           senderAddress:(::djinni::String::fromCpp(cpp.senderAddress))
                                            dateReceived:(::ObjCpp::Kullo::Api::DateTime::fromCpp(cpp.dateReceived))
                                                 snippet:(::djinni::String::fromCpp(cpp.snippet))
                                                boundary:(::djinni::String::fromCpp(cpp.boundary))];
}

} } }  // namespace ObjCpp::Kullo::Api
