// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#include "kulloclient/api/Messages.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KAMessages;

namespace ObjCpp { namespace Kullo { namespace Api {

class Messages
{
public:
    using CppType = std::shared_ptr<::Kullo::Api::Messages>;
    using ObjcType = KAMessages*;

    using Boxed = Messages;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

