// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import <Foundation/Foundation.h>


/** Listener used in MessageAttachments.contentAsync() */
@protocol KAMessageAttachmentsContentListener

- (void)finished:(int64_t)msgId
           attId:(int64_t)attId
         content:(nonnull NSData *)content;

@end
