// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#include "kulloclient/api/MessageAttachmentsSaveToListener.h"
#include <kulloclient/nn.h>
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol KAMessageAttachmentsSaveToListener;

namespace ObjCpp { namespace Kullo { namespace Api {

class MessageAttachmentsSaveToListener
{
public:
    using CppType = ::Kullo::nn_shared_ptr<::Kullo::Api::MessageAttachmentsSaveToListener>;
    using CppOptType = std::shared_ptr<::Kullo::Api::MessageAttachmentsSaveToListener>;
    using ObjcType = id<KAMessageAttachmentsSaveToListener>;

    using Boxed = MessageAttachmentsSaveToListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

