// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import "KADateTime.h"
#import "KASenderPredicate.h"
#import <Foundation/Foundation.h>
@class KAAddress;
@class KAAsyncTask;
@class KADelivery;
@protocol KAMessagesSearchListener;


@interface KAMessages : NSObject

/** Returns all messages for the given conversation */
- (nonnull NSArray<NSNumber *> *)allForConversation:(int64_t)convId;

/**
 * Returns the message id of the latest record for the given sender address.
 * Returns -1 for addresses without a sender record.
 */
- (int64_t)latestForSender:(nullable KAAddress *)address;

/** Deletes a message */
- (void)remove:(int64_t)msgId;

- (int64_t)conversation:(int64_t)msgId;

- (nonnull NSArray<KADelivery *> *)deliveryState:(int64_t)msgId;

- (BOOL)isRead:(int64_t)msgId;

/** returns true iff value changed in this call */
- (BOOL)setRead:(int64_t)msgId
          value:(BOOL)value;

- (BOOL)isDone:(int64_t)msgId;

/** returns true iff value changed in this call */
- (BOOL)setDone:(int64_t)msgId
          value:(BOOL)value;

- (nonnull KADateTime *)dateSent:(int64_t)msgId;

- (nonnull KADateTime *)dateReceived:(int64_t)msgId;

- (nonnull NSString *)text:(int64_t)msgId;

/**
 * Escapes special characters and wraps links into 'a' tags
 *
 * An application using this must preserve the whitespace in the HTML code,
 * i.e. treat \n and \r\n as line breaks and not strip leading or trailing
 * spaces in lines.
 * This can be archived for example by wrapping this in a html block with
 * style "white-space: pre-wrap;".
 *
 * When includeKulloAddresses is true, Kullo addresses are linked using the
 * Kullo internal scheme "kulloInternal:" followed by the unescaped address.
 * Those links must be handled by the Kullo client and must not be passed to
 * other applications since the URI scheme is not standardized and the hash
 * symbol is not compatible with a lot of applications.
 *
 * Web links are prioritized over Kullo address links and links do not overlap.
 */
- (nonnull NSString *)textAsHtml:(int64_t)msgId
           includeKulloAddresses:(BOOL)includeKulloAddresses;

- (nonnull NSString *)footer:(int64_t)msgId;

/**
 * Full-text search for messages
 *
 * searchText: The text to search for. Does prefix matching.
 * convId: Conversation ID to filter by conversation, or -1 to search all.
 * sender: Filter by sender, if set.
 * boundary: boundary used in result highlighting; auto-generated if unset
 * limitResults: The maximum number of results to return.
 */
- (nullable KAAsyncTask *)searchAsync:(nonnull NSString *)searchText
                               convId:(int64_t)convId
                               sender:(nullable KASenderPredicate *)sender
                         limitResults:(int32_t)limitResults
                             boundary:(nullable NSString *)boundary
                             listener:(nullable id<KAMessagesSearchListener>)listener;

@end
