// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import "KADateTime.h"
#import <Foundation/Foundation.h>
@class KAAddress;
@class KADelivery;


@interface KAMessages : NSObject

/** Returns all messages for the given conversation */
- (nonnull NSArray<NSNumber *> *)allForConversation:(int64_t)convId;

/**
 * Returns the message id of the latest record for the given sender address.
 * Returns -1 for addresses without a sender record.
 */
- (int64_t)latestForSender:(nullable KAAddress *)address;

/** Deletes a message */
- (void)remove:(int64_t)msgId;

- (int64_t)conversation:(int64_t)msgId;

- (nonnull NSArray<KADelivery *> *)deliveryState:(int64_t)msgId;

- (BOOL)isRead:(int64_t)msgId;

- (void)setRead:(int64_t)msgId
          value:(BOOL)value;

- (BOOL)isDone:(int64_t)msgId;

- (void)setDone:(int64_t)msgId
          value:(BOOL)value;

- (nonnull KADateTime *)dateSent:(int64_t)msgId;

- (nonnull KADateTime *)dateReceived:(int64_t)msgId;

- (nonnull NSString *)text:(int64_t)msgId;

/** Escapes special characters and converts text links to 'a' tags */
- (nonnull NSString *)textAsHtml:(int64_t)msgId;

- (nonnull NSString *)footer:(int64_t)msgId;

@end
