// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import <Foundation/Foundation.h>
@class KAAsyncTask;
@protocol KAMessageAttachmentsContentListener;
@protocol KAMessageAttachmentsSaveToListener;


@interface KAMessageAttachments : NSObject

/** Returns all attachments for the given message */
- (nonnull NSArray<NSNumber *> *)allForMessage:(int64_t)msgId;

/**
 * Returns true iff all attachments of the given message have been downloaded
 * (see Syncer for how to download attachments)
 */
- (BOOL)allAttachmentsDownloaded:(int64_t)msgId;

/** Filename (e.g. "hello.png") */
- (nonnull NSString *)filename:(int64_t)msgId
                         attId:(int64_t)attId;

/** MIME type (e.g. "image/png") */
- (nonnull NSString *)mimeType:(int64_t)msgId
                         attId:(int64_t)attId;

/** File size in bytes */
- (int64_t)size:(int64_t)msgId
          attId:(int64_t)attId;

/** SHA-512 hash of the attachment contents */
- (nonnull NSString *)hash:(int64_t)msgId
                     attId:(int64_t)attId;

/** Gets the content of the attachment as a BLOB */
- (nullable KAAsyncTask *)contentAsync:(int64_t)msgId
                                 attId:(int64_t)attId
                              listener:(nullable id<KAMessageAttachmentsContentListener>)listener;

/**
 * Saves the content of the attachment to a file. Path contains the absolute
 * path where the file should be saved, including the filename.
 */
- (nullable KAAsyncTask *)saveToAsync:(int64_t)msgId
                                attId:(int64_t)attId
                                 path:(nonnull NSString *)path
                             listener:(nullable id<KAMessageAttachmentsSaveToListener>)listener;

@end
