// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import "KAMessageAttachmentsSaveToListener+Private.h"
#import "KAMessageAttachmentsSaveToListener.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "KALocalError+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace ObjCpp { namespace Kullo { namespace Api {

class MessageAttachmentsSaveToListener::ObjcProxy final
: public ::Kullo::Api::MessageAttachmentsSaveToListener
, public ::djinni::ObjcProxyCache::Handle<ObjcType>
{
public:
    using Handle::Handle;
    void finished(int64_t c_msgId, int64_t c_attId, const std::string & c_path) override
    {
        @autoreleasepool {
            [Handle::get() finished:(::djinni::I64::fromCpp(c_msgId))
                              attId:(::djinni::I64::fromCpp(c_attId))
                               path:(::djinni::String::fromCpp(c_path))];
        }
    }
    void error(int64_t c_msgId, int64_t c_attId, const std::string & c_path, ::Kullo::Api::LocalError c_error) override
    {
        @autoreleasepool {
            [Handle::get() error:(::djinni::I64::fromCpp(c_msgId))
                           attId:(::djinni::I64::fromCpp(c_attId))
                            path:(::djinni::String::fromCpp(c_path))
                           error:(::djinni::Enum<::Kullo::Api::LocalError, KALocalError>::fromCpp(c_error))];
        }
    }
};

} } }  // namespace ObjCpp::Kullo::Api

namespace ObjCpp { namespace Kullo { namespace Api {

auto MessageAttachmentsSaveToListener::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto MessageAttachmentsSaveToListener::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).Handle::get();
}

} } }  // namespace ObjCpp::Kullo::Api
