// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#include "kulloclient/api/MessageAttachmentsSaveToListener.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol KAMessageAttachmentsSaveToListener;

namespace ObjCpp { namespace Kullo { namespace Api {

class MessageAttachmentsSaveToListener
{
public:
    using CppType = std::shared_ptr<::Kullo::Api::MessageAttachmentsSaveToListener>;
    using ObjcType = id<KAMessageAttachmentsSaveToListener>;

    using Boxed = MessageAttachmentsSaveToListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

