// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from errors.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, KANetworkError)
{
    /** Client too old or otherwise blocked; should check for update */
    KANetworkErrorForbidden,
    /** Client and server protocol incompatible; should check for update */
    KANetworkErrorProtocol,
    /** Bad login info (address + master key) */
    KANetworkErrorUnauthorized,
    /** Server-side error */
    KANetworkErrorServer,
    /** Network connection couldn't be established */
    KANetworkErrorConnection,
    /** Any other error */
    KANetworkErrorUnknown,
};
