// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from push.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, KAPushTokenType)
{
    /** Google Cloud Messaging */
    KAPushTokenTypeGCM,
    /** Apple Push Notification Service */
    KAPushTokenTypeAPNS,
};
