// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from push.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, KAPushTokenEnvironment)
{
    /** GCM: when run on Android */
    KAPushTokenEnvironmentAndroid,
    /** GCM: when run on iOS */
    KAPushTokenEnvironmentIOS,
    /** APNS: when aps-environment=development */
    KAPushTokenEnvironmentDevelopment,
    /** APNS: when aps-environment=production */
    KAPushTokenEnvironmentProduction,
};
