// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from push.djinni

#import "KAPushToken.h"
#include "kulloclient/api/PushToken.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KAPushToken;

namespace ObjCpp { namespace Kullo { namespace Api {

struct PushToken
{
    using CppType = ::Kullo::Api::PushToken;
    using ObjcType = KAPushToken*;

    using Boxed = PushToken;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} } }  // namespace ObjCpp::Kullo::Api
