// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from push.djinni

#import "KAPushTokenEnvironment.h"
#import "KAPushTokenType.h"
#import <Foundation/Foundation.h>

@interface KAPushToken : NSObject
- (nonnull instancetype)initWithType:(KAPushTokenType)type
                               token:(nonnull NSString *)token
                         environment:(KAPushTokenEnvironment)environment;
+ (nonnull instancetype)PushTokenWithType:(KAPushTokenType)type
                                    token:(nonnull NSString *)token
                              environment:(KAPushTokenEnvironment)environment;

@property (nonatomic, readonly) KAPushTokenType type;

/** GCM: the token; APNS: the hex-encoded token */
@property (nonatomic, readonly, nonnull) NSString * token;

@property (nonatomic, readonly) KAPushTokenEnvironment environment;

@end
