// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from push.djinni

#import "KAPushToken.h"


@implementation KAPushToken

- (nonnull instancetype)initWithType:(KAPushTokenType)type
                               token:(nonnull NSString *)token
                         environment:(KAPushTokenEnvironment)environment
{
    if (self = [super init]) {
        _type = type;
        _token = [token copy];
        _environment = environment;
    }
    return self;
}

+ (nonnull instancetype)PushTokenWithType:(KAPushTokenType)type
                                    token:(nonnull NSString *)token
                              environment:(KAPushTokenEnvironment)environment
{
    return [[self alloc] initWithType:type
                                token:token
                          environment:environment];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p type:%@ token:%@ environment:%@>", self.class, (void *)self, @(self.type), self.token, @(self.environment)];
}

@end
