// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from registration.djinni

#import "KAAddressNotAvailableReason.h"
#import "KANetworkError.h"
#import <Foundation/Foundation.h>
@class KAAddress;
@class KAChallenge;
@class KAMasterKey;


/** Listener used in Registration.registerAccountAsync() */
@protocol KARegistrationRegisterAccountListener

- (void)challengeNeeded:(nullable KAAddress *)address
              challenge:(nullable KAChallenge *)challenge;

- (void)addressNotAvailable:(nullable KAAddress *)address
                     reason:(KAAddressNotAvailableReason)reason;

- (void)finished:(nullable KAAddress *)address
       masterKey:(nullable KAMasterKey *)masterKey;

- (void)error:(nullable KAAddress *)address
        error:(KANetworkError)error;

@end
