// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from registration.djinni

#import "KAAddress.h"
#import <Foundation/Foundation.h>
@class KAAsyncTask;
@class KAChallenge;
@protocol KARegistrationRegisterAccountListener;


/** Can be obtained through Client.generateKeysAsync(). */
@interface KARegistration : NSObject

/**
 * Register a new account.
 *
 * acceptedTerms is the url of the accepted terms of service.
 * Set null if no terms are accepted.
 *
 * Set challenge to the value passed to
 * RegistrationRegisterAccountListener::challengeNeeded if you recently sent
 * a registration request for the same address that failed because of a
 * missing or wrong challenge answer. Otherwise, just pass null.
 *
 * If no challenge is needed, set challengeAnswer to ""
 */
- (nonnull KAAsyncTask *)registerAccountAsync:(nonnull KAAddress *)address
                                acceptedTerms:(nullable NSString *)acceptedTerms
                                    challenge:(nullable KAChallenge *)challenge
                              challengeAnswer:(nonnull NSString *)challengeAnswer
                                     listener:(nonnull id<KARegistrationRegisterAccountListener>)listener;

@end
