// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from registry.djinni

#import <Foundation/Foundation.h>
@protocol KALogListener;
@protocol KATaskRunner;


/** Registry for helpers that are used by libkullo. */
@interface KARegistry : NSObject

/**
 * Sets the log listener. If null is passed, default behavior is restored,
 * which means writing the log messages to stdout.
 */
+ (void)setLogListener:(nullable id<KALogListener>)listener;

/** Sets a new TaskRunner. Must be done before any async method is called. */
+ (void)setTaskRunner:(nonnull id<KATaskRunner>)taskRunner;

@end
