// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from registration.djinni

#include "kulloclient/api/Registration.h"
#include <kulloclient/nn.h>
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KARegistration;

namespace ObjCpp { namespace Kullo { namespace Api {

class Registration
{
public:
    using CppType = ::Kullo::nn_shared_ptr<::Kullo::Api::Registration>;
    using CppOptType = std::shared_ptr<::Kullo::Api::Registration>;
    using ObjcType = KARegistration*;

    using Boxed = Registration;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

