// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "KARegistry+Private.h"
#import "KARegistry.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "KALogListener+Private.h"
#import "KATaskRunner+Private.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface KARegistry ()

- (id)initWithCpp:(const std::shared_ptr<::Kullo::Api::Registry>&)cppRef;

@end

@implementation KARegistry {
    ::djinni::DbxCppWrapperCache<::Kullo::Api::Registry>::Handle _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::Kullo::Api::Registry>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (void)setLogListener:(nullable id<KALogListener>)listener {
    try {
        ::Kullo::Api::Registry::setLogListener(::ObjCpp::Kullo::Api::LogListener::toCpp(listener));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (void)setTaskRunner:(nullable id<KATaskRunner>)taskRunner {
    try {
        ::Kullo::Api::Registry::setTaskRunner(::ObjCpp::Kullo::Api::TaskRunner::toCpp(taskRunner));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace ObjCpp { namespace Kullo { namespace Api {

auto Registry::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Registry::fromCpp(const CppType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::DbxCppWrapperCache<::Kullo::Api::Registry>::getInstance()->get(cpp, [] (const CppType& p) {
        return [[KARegistry alloc] initWithCpp:p];
    });
}

} } }  // namespace ObjCpp::Kullo::Api

@end
