// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from registration.djinni

#import "KAAddress.h"
#import "KAAddressNotAvailableReason.h"
#import "KAMasterKey.h"
#import "KANetworkError.h"
#import <Foundation/Foundation.h>
@class KAChallenge;


/** Listener used in Registration.registerAccountAsync() */
@protocol KARegistrationRegisterAccountListener

- (void)challengeNeeded:(nonnull KAAddress *)address
              challenge:(nonnull KAChallenge *)challenge;

- (void)addressNotAvailable:(nonnull KAAddress *)address
                     reason:(KAAddressNotAvailableReason)reason;

- (void)finished:(nonnull KAAddress *)address
       masterKey:(nonnull KAMasterKey *)masterKey;

- (void)error:(nonnull KAAddress *)address
        error:(KANetworkError)error;

@end
