// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from registration.djinni

#include "kulloclient/api/RegistrationRegisterAccountListener.h"
#include <kulloclient/nn.h>
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol KARegistrationRegisterAccountListener;

namespace ObjCpp { namespace Kullo { namespace Api {

class RegistrationRegisterAccountListener
{
public:
    using CppType = ::Kullo::nn_shared_ptr<::Kullo::Api::RegistrationRegisterAccountListener>;
    using CppOptType = std::shared_ptr<::Kullo::Api::RegistrationRegisterAccountListener>;
    using ObjcType = id<KARegistrationRegisterAccountListener>;

    using Boxed = RegistrationRegisterAccountListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

