// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import "KASenderPredicate.h"
#include "kulloclient/api/SenderPredicate.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KASenderPredicate;

namespace ObjCpp { namespace Kullo { namespace Api {

struct SenderPredicate
{
    using CppType = ::Kullo::Api::SenderPredicate;
    using ObjcType = KASenderPredicate*;

    using Boxed = SenderPredicate;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} } }  // namespace ObjCpp::Kullo::Api
