// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import "KASenderPredicate.h"


@implementation KASenderPredicate

- (nonnull instancetype)initWithPredicateOperator:(KASearchPredicateOperator)predicateOperator
                                    senderAddress:(nonnull NSString *)senderAddress
{
    if (self = [super init]) {
        _predicateOperator = predicateOperator;
        _senderAddress = [senderAddress copy];
    }
    return self;
}

+ (nonnull instancetype)SenderPredicateWithPredicateOperator:(KASearchPredicateOperator)predicateOperator
                                               senderAddress:(nonnull NSString *)senderAddress
{
    return [[self alloc] initWithPredicateOperator:predicateOperator
                                     senderAddress:senderAddress];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p predicateOperator:%@ senderAddress:%@>", self.class, (void *)self, @(self.predicateOperator), self.senderAddress];
}

@end
