// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from session.djinni

#import "KAEvent.h"
#import "KAPushToken.h"
#import <Foundation/Foundation.h>
@class KAAsyncTask;
@class KAConversations;
@class KADraftAttachments;
@class KADrafts;
@class KAInternalEvent;
@class KAMessageAttachments;
@class KAMessages;
@class KASenders;
@class KASyncer;
@class KAUserSettings;
@protocol KASessionAccountInfoListener;


@interface KASession : NSObject

- (nonnull KAUserSettings *)userSettings;

- (nonnull KAConversations *)conversations;

- (nonnull KAMessages *)messages;

- (nonnull KAMessageAttachments *)messageAttachments;

- (nonnull KASenders *)senders;

- (nonnull KADrafts *)drafts;

- (nonnull KADraftAttachments *)draftAttachments;

- (nonnull KASyncer *)syncer;

- (nonnull KAAsyncTask *)accountInfoAsync:(nonnull id<KASessionAccountInfoListener>)listener;

- (nonnull KAAsyncTask *)registerPushToken:(nonnull KAPushToken *)token;

- (nonnull KAAsyncTask *)unregisterPushToken:(nonnull KAPushToken *)token;

/** Notify the session of events. Only call this from the UI thread! */
- (nonnull NSArray<KAEvent *> *)notify:(nonnull KAInternalEvent *)internalEvent;

@end
