// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "KAEvent.h"
#import <Foundation/Foundation.h>
@class KAAsyncTask;
@class KAConversations;
@class KADraftAttachments;
@class KADrafts;
@class KAInternalEvent;
@class KAMessageAttachments;
@class KAMessages;
@class KASenders;
@class KASyncer;
@class KAUserSettings;
@protocol KASessionAccountInfoListener;


@interface KASession : NSObject

- (nullable KAUserSettings *)userSettings;

- (nullable KAConversations *)conversations;

- (nullable KAMessages *)messages;

- (nullable KAMessageAttachments *)messageAttachments;

- (nullable KASenders *)senders;

- (nullable KADrafts *)drafts;

- (nullable KADraftAttachments *)draftAttachments;

- (nullable KASyncer *)syncer;

- (nullable KAAsyncTask *)accountInfoAsync:(nullable id<KASessionAccountInfoListener>)listener;

/** Notify the session of events. Only call this from the UI thread! */
- (nonnull NSArray *)notify:(nullable KAInternalEvent *)internalEvent;

@end
