// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from session.djinni

#import "KASessionAccountInfoListener+Private.h"
#import "KASessionAccountInfoListener.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "KAAccountInfo+Private.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace ObjCpp { namespace Kullo { namespace Api {

class SessionAccountInfoListener::ObjcProxy final
: public ::Kullo::Api::SessionAccountInfoListener
, public ::djinni::ObjcProxyCache::Handle<ObjcType>
{
public:
    using Handle::Handle;
    void finished(const ::Kullo::Api::AccountInfo & c_accountInfo) override
    {
        @autoreleasepool {
            [Handle::get() finished:(::ObjCpp::Kullo::Api::AccountInfo::fromCpp(c_accountInfo))];
        }
    }
    void error(::Kullo::Api::NetworkError c_error) override
    {
        @autoreleasepool {
            [Handle::get() error:(::djinni::Enum<::Kullo::Api::NetworkError, KANetworkError>::fromCpp(c_error))];
        }
    }
};

} } }  // namespace ObjCpp::Kullo::Api

namespace ObjCpp { namespace Kullo { namespace Api {

auto SessionAccountInfoListener::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto SessionAccountInfoListener::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).Handle::get();
}

} } }  // namespace ObjCpp::Kullo::Api
