// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from session.djinni

#include "kulloclient/api/SessionAccountInfoListener.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol KASessionAccountInfoListener;

namespace ObjCpp { namespace Kullo { namespace Api {

class SessionAccountInfoListener
{
public:
    using CppType = std::shared_ptr<::Kullo::Api::SessionAccountInfoListener>;
    using CppOptType = std::shared_ptr<::Kullo::Api::SessionAccountInfoListener>;
    using ObjcType = id<KASessionAccountInfoListener>;

    using Boxed = SessionAccountInfoListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

