// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import "KASenderPredicate+Private.h"
#import "DJIMarshal+Private.h"
#import "KASearchPredicateOperator+Private.h"
#include <cassert>

namespace ObjCpp { namespace Kullo { namespace Api {

auto SenderPredicate::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Enum<::Kullo::Api::SearchPredicateOperator, KASearchPredicateOperator>::toCpp(obj.predicateOperator),
            ::djinni::String::toCpp(obj.senderAddress)};
}

auto SenderPredicate::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[KASenderPredicate alloc] initWithPredicateOperator:(::djinni::Enum<::Kullo::Api::SearchPredicateOperator, KASearchPredicateOperator>::fromCpp(cpp.predicateOperator))
                                                  senderAddress:(::djinni::String::fromCpp(cpp.senderAddress))];
}

} } }  // namespace ObjCpp::Kullo::Api
