// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import <Foundation/Foundation.h>
@class KAAddress;


@interface KASenders : NSObject

- (nonnull NSString *)name:(int64_t)msgId;

/** Returns null if the msgId is invalid */
- (nullable KAAddress *)address:(int64_t)msgId;

- (nonnull NSString *)organization:(int64_t)msgId;

- (nonnull NSString *)avatarMimeType:(int64_t)msgId;

- (nonnull NSData *)avatar:(int64_t)msgId;

@end
