// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#import "KASearchPredicateOperator.h"
#import <Foundation/Foundation.h>

@interface KASenderPredicate : NSObject
- (nonnull instancetype)initWithPredicateOperator:(KASearchPredicateOperator)predicateOperator
                                    senderAddress:(nonnull NSString *)senderAddress;
+ (nonnull instancetype)SenderPredicateWithPredicateOperator:(KASearchPredicateOperator)predicateOperator
                                               senderAddress:(nonnull NSString *)senderAddress;

@property (nonatomic, readonly) KASearchPredicateOperator predicateOperator;

@property (nonatomic, readonly, nonnull) NSString * senderAddress;

@end
