// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#include "kulloclient/api/SyncerRunListener.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol KASyncerRunListener;

namespace ObjCpp { namespace Kullo { namespace Api {

class SyncerRunListener
{
public:
    using CppType = std::shared_ptr<::Kullo::Api::SyncerRunListener>;
    using ObjcType = id<KASyncerRunListener>;

    using Boxed = SyncerRunListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

