// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

#import "KASyncPhase.h"
#import <Foundation/Foundation.h>

/** Encodes a progress update during syncing. Unknown totals are set to 0. */
@interface KASyncProgress : NSObject
- (nonnull instancetype)initWithPhase:(KASyncPhase)phase
            incomingMessagesProcessed:(int64_t)incomingMessagesProcessed
                incomingMessagesTotal:(int64_t)incomingMessagesTotal
                  incomingMessagesNew:(int64_t)incomingMessagesNew
            incomingMessagesNewUnread:(int64_t)incomingMessagesNewUnread
             incomingMessagesModified:(int64_t)incomingMessagesModified
              incomingMessagesDeleted:(int64_t)incomingMessagesDeleted
   incomingAttachmentsDownloadedBytes:(int64_t)incomingAttachmentsDownloadedBytes
        incomingAttachmentsTotalBytes:(int64_t)incomingAttachmentsTotalBytes
        outgoingMessagesUploadedBytes:(int64_t)outgoingMessagesUploadedBytes
           outgoingMessagesTotalBytes:(int64_t)outgoingMessagesTotalBytes
                            runTimeMs:(int64_t)runTimeMs;
+ (nonnull instancetype)SyncProgressWithPhase:(KASyncPhase)phase
                    incomingMessagesProcessed:(int64_t)incomingMessagesProcessed
                        incomingMessagesTotal:(int64_t)incomingMessagesTotal
                          incomingMessagesNew:(int64_t)incomingMessagesNew
                    incomingMessagesNewUnread:(int64_t)incomingMessagesNewUnread
                     incomingMessagesModified:(int64_t)incomingMessagesModified
                      incomingMessagesDeleted:(int64_t)incomingMessagesDeleted
           incomingAttachmentsDownloadedBytes:(int64_t)incomingAttachmentsDownloadedBytes
                incomingAttachmentsTotalBytes:(int64_t)incomingAttachmentsTotalBytes
                outgoingMessagesUploadedBytes:(int64_t)outgoingMessagesUploadedBytes
                   outgoingMessagesTotalBytes:(int64_t)outgoingMessagesTotalBytes
                                    runTimeMs:(int64_t)runTimeMs;

@property (nonatomic, readonly) KASyncPhase phase;

/** inbox (unit: messages) */
@property (nonatomic, readonly) int64_t incomingMessagesProcessed;

@property (nonatomic, readonly) int64_t incomingMessagesTotal;

@property (nonatomic, readonly) int64_t incomingMessagesNew;

@property (nonatomic, readonly) int64_t incomingMessagesNewUnread;

@property (nonatomic, readonly) int64_t incomingMessagesModified;

@property (nonatomic, readonly) int64_t incomingMessagesDeleted;

/** incoming attachments (unit: bytes) */
@property (nonatomic, readonly) int64_t incomingAttachmentsDownloadedBytes;

@property (nonatomic, readonly) int64_t incomingAttachmentsTotalBytes;

/** outgoing messages + attachments (unit: uncompressed bytes) */
@property (nonatomic, readonly) int64_t outgoingMessagesUploadedBytes;

@property (nonatomic, readonly) int64_t outgoingMessagesTotalBytes;

/** Run time of the current sync (unit: milliseconds) */
@property (nonatomic, readonly) int64_t runTimeMs;

@end
