// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

#import "KASyncProgress+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace ObjCpp { namespace Kullo { namespace Api {

auto SyncProgress::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I64::toCpp(obj.countLeft),
            ::djinni::I64::toCpp(obj.countProcessed),
            ::djinni::I64::toCpp(obj.countTotal),
            ::djinni::I64::toCpp(obj.countNew),
            ::djinni::I64::toCpp(obj.countNewUnread),
            ::djinni::I64::toCpp(obj.countModified),
            ::djinni::I64::toCpp(obj.countDeleted),
            ::djinni::I64::toCpp(obj.runTimeMs)};
}

auto SyncProgress::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[KASyncProgress alloc] initWithCountLeft:(::djinni::I64::fromCpp(cpp.countLeft))
                                      countProcessed:(::djinni::I64::fromCpp(cpp.countProcessed))
                                          countTotal:(::djinni::I64::fromCpp(cpp.countTotal))
                                            countNew:(::djinni::I64::fromCpp(cpp.countNew))
                                      countNewUnread:(::djinni::I64::fromCpp(cpp.countNewUnread))
                                       countModified:(::djinni::I64::fromCpp(cpp.countModified))
                                        countDeleted:(::djinni::I64::fromCpp(cpp.countDeleted))
                                           runTimeMs:(::djinni::I64::fromCpp(cpp.runTimeMs))];
}

} } }  // namespace ObjCpp::Kullo::Api
