// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, KASyncMode)
{
    /** Do the minimal work required to send all unsent prepared drafts */
    KASyncModeSendOnly,
    /** Sync everything, but don't download attachments */
    KASyncModeWithoutAttachments,
    /** Sync everything, including attachments */
    KASyncModeEverything,
};
