// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

#import "KASyncProgress.h"
#include "kulloclient/api/SyncProgress.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KASyncProgress;

namespace ObjCpp { namespace Kullo { namespace Api {

struct SyncProgress
{
    using CppType = ::Kullo::Api::SyncProgress;
    using ObjcType = KASyncProgress*;

    using Boxed = SyncProgress;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} } }  // namespace ObjCpp::Kullo::Api
