// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

#import "KASyncProgress.h"


@implementation KASyncProgress

- (nonnull instancetype)initWithCountLeft:(int64_t)countLeft
                           countProcessed:(int64_t)countProcessed
                               countTotal:(int64_t)countTotal
                                 countNew:(int64_t)countNew
                           countNewUnread:(int64_t)countNewUnread
                            countModified:(int64_t)countModified
                             countDeleted:(int64_t)countDeleted
                                runTimeMs:(int64_t)runTimeMs
{
    if (self = [super init]) {
        _countLeft = countLeft;
        _countProcessed = countProcessed;
        _countTotal = countTotal;
        _countNew = countNew;
        _countNewUnread = countNewUnread;
        _countModified = countModified;
        _countDeleted = countDeleted;
        _runTimeMs = runTimeMs;
    }
    return self;
}

+ (nonnull instancetype)SyncProgressWithCountLeft:(int64_t)countLeft
                                   countProcessed:(int64_t)countProcessed
                                       countTotal:(int64_t)countTotal
                                         countNew:(int64_t)countNew
                                   countNewUnread:(int64_t)countNewUnread
                                    countModified:(int64_t)countModified
                                     countDeleted:(int64_t)countDeleted
                                        runTimeMs:(int64_t)runTimeMs
{
    return [[self alloc] initWithCountLeft:countLeft
                            countProcessed:countProcessed
                                countTotal:countTotal
                                  countNew:countNew
                            countNewUnread:countNewUnread
                             countModified:countModified
                              countDeleted:countDeleted
                                 runTimeMs:runTimeMs];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p countLeft:%@ countProcessed:%@ countTotal:%@ countNew:%@ countNewUnread:%@ countModified:%@ countDeleted:%@ runTimeMs:%@>", self.class, (void *)self, @(self.countLeft), @(self.countProcessed), @(self.countTotal), @(self.countNew), @(self.countNewUnread), @(self.countModified), @(self.countDeleted), @(self.runTimeMs)];
}

@end
