// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, KASyncPhase)
{
    KASyncPhaseKeys,
    KASyncPhaseProfile,
    /** Downloading and processing of incoming messages */
    KASyncPhaseIncomingMessages,
    /** Downloading and processing of attachments */
    KASyncPhaseIncomingAttachments,
    /** Sending messages */
    KASyncPhaseOutgoingMessages,
};
