// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "KANetworkError.h"
#import <Foundation/Foundation.h>


/** Listener used in Syncer.runAsync() */
@protocol KASyncerRunListener

- (void)draftAttachmentsTooBig:(int64_t)convId;

- (void)finished;

- (void)error:(KANetworkError)error;

@end
