// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

#import <Foundation/Foundation.h>

@interface KASyncProgress : NSObject
- (nonnull instancetype)initWithCountLeft:(int64_t)countLeft
                           countProcessed:(int64_t)countProcessed
                               countTotal:(int64_t)countTotal
                                 countNew:(int64_t)countNew
                           countNewUnread:(int64_t)countNewUnread
                            countModified:(int64_t)countModified
                             countDeleted:(int64_t)countDeleted
                                runTimeMs:(int64_t)runTimeMs;
+ (nonnull instancetype)SyncProgressWithCountLeft:(int64_t)countLeft
                                   countProcessed:(int64_t)countProcessed
                                       countTotal:(int64_t)countTotal
                                         countNew:(int64_t)countNew
                                   countNewUnread:(int64_t)countNewUnread
                                    countModified:(int64_t)countModified
                                     countDeleted:(int64_t)countDeleted
                                        runTimeMs:(int64_t)runTimeMs;

/** stats about messages */
@property (nonatomic, readonly) int64_t countLeft;

@property (nonatomic, readonly) int64_t countProcessed;

@property (nonatomic, readonly) int64_t countTotal;

@property (nonatomic, readonly) int64_t countNew;

@property (nonatomic, readonly) int64_t countNewUnread;

@property (nonatomic, readonly) int64_t countModified;

@property (nonatomic, readonly) int64_t countDeleted;

/** Run time of the current sync in milliseconds */
@property (nonatomic, readonly) int64_t runTimeMs;

@end
