// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

#import "KASyncProgress.h"


@implementation KASyncProgress

- (nonnull instancetype)initWithPhase:(KASyncPhase)phase
            incomingMessagesProcessed:(int64_t)incomingMessagesProcessed
                incomingMessagesTotal:(int64_t)incomingMessagesTotal
                  incomingMessagesNew:(int64_t)incomingMessagesNew
            incomingMessagesNewUnread:(int64_t)incomingMessagesNewUnread
             incomingMessagesModified:(int64_t)incomingMessagesModified
              incomingMessagesDeleted:(int64_t)incomingMessagesDeleted
   incomingAttachmentsDownloadedBytes:(int64_t)incomingAttachmentsDownloadedBytes
        incomingAttachmentsTotalBytes:(int64_t)incomingAttachmentsTotalBytes
                  incomingAttachments:(nonnull NSDictionary<NSNumber *, KAAttachmentsBlockDownloadProgress *> *)incomingAttachments
        outgoingMessagesUploadedBytes:(int64_t)outgoingMessagesUploadedBytes
           outgoingMessagesTotalBytes:(int64_t)outgoingMessagesTotalBytes
                            runTimeMs:(int64_t)runTimeMs
{
    if (self = [super init]) {
        _phase = phase;
        _incomingMessagesProcessed = incomingMessagesProcessed;
        _incomingMessagesTotal = incomingMessagesTotal;
        _incomingMessagesNew = incomingMessagesNew;
        _incomingMessagesNewUnread = incomingMessagesNewUnread;
        _incomingMessagesModified = incomingMessagesModified;
        _incomingMessagesDeleted = incomingMessagesDeleted;
        _incomingAttachmentsDownloadedBytes = incomingAttachmentsDownloadedBytes;
        _incomingAttachmentsTotalBytes = incomingAttachmentsTotalBytes;
        _incomingAttachments = [incomingAttachments copy];
        _outgoingMessagesUploadedBytes = outgoingMessagesUploadedBytes;
        _outgoingMessagesTotalBytes = outgoingMessagesTotalBytes;
        _runTimeMs = runTimeMs;
    }
    return self;
}

+ (nonnull instancetype)SyncProgressWithPhase:(KASyncPhase)phase
                    incomingMessagesProcessed:(int64_t)incomingMessagesProcessed
                        incomingMessagesTotal:(int64_t)incomingMessagesTotal
                          incomingMessagesNew:(int64_t)incomingMessagesNew
                    incomingMessagesNewUnread:(int64_t)incomingMessagesNewUnread
                     incomingMessagesModified:(int64_t)incomingMessagesModified
                      incomingMessagesDeleted:(int64_t)incomingMessagesDeleted
           incomingAttachmentsDownloadedBytes:(int64_t)incomingAttachmentsDownloadedBytes
                incomingAttachmentsTotalBytes:(int64_t)incomingAttachmentsTotalBytes
                          incomingAttachments:(nonnull NSDictionary<NSNumber *, KAAttachmentsBlockDownloadProgress *> *)incomingAttachments
                outgoingMessagesUploadedBytes:(int64_t)outgoingMessagesUploadedBytes
                   outgoingMessagesTotalBytes:(int64_t)outgoingMessagesTotalBytes
                                    runTimeMs:(int64_t)runTimeMs
{
    return [[self alloc] initWithPhase:phase
             incomingMessagesProcessed:incomingMessagesProcessed
                 incomingMessagesTotal:incomingMessagesTotal
                   incomingMessagesNew:incomingMessagesNew
             incomingMessagesNewUnread:incomingMessagesNewUnread
              incomingMessagesModified:incomingMessagesModified
               incomingMessagesDeleted:incomingMessagesDeleted
    incomingAttachmentsDownloadedBytes:incomingAttachmentsDownloadedBytes
         incomingAttachmentsTotalBytes:incomingAttachmentsTotalBytes
                   incomingAttachments:incomingAttachments
         outgoingMessagesUploadedBytes:outgoingMessagesUploadedBytes
            outgoingMessagesTotalBytes:outgoingMessagesTotalBytes
                             runTimeMs:runTimeMs];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p phase:%@ incomingMessagesProcessed:%@ incomingMessagesTotal:%@ incomingMessagesNew:%@ incomingMessagesNewUnread:%@ incomingMessagesModified:%@ incomingMessagesDeleted:%@ incomingAttachmentsDownloadedBytes:%@ incomingAttachmentsTotalBytes:%@ incomingAttachments:%@ outgoingMessagesUploadedBytes:%@ outgoingMessagesTotalBytes:%@ runTimeMs:%@>", self.class, (void *)self, @(self.phase), @(self.incomingMessagesProcessed), @(self.incomingMessagesTotal), @(self.incomingMessagesNew), @(self.incomingMessagesNewUnread), @(self.incomingMessagesModified), @(self.incomingMessagesDeleted), @(self.incomingAttachmentsDownloadedBytes), @(self.incomingAttachmentsTotalBytes), self.incomingAttachments, @(self.outgoingMessagesUploadedBytes), @(self.outgoingMessagesTotalBytes), @(self.runTimeMs)];
}

@end
