// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

#import "KASyncMode.h"
#import <Foundation/Foundation.h>
@class KAAsyncTask;
@protocol KASyncerListener;


/**
 * Handles syncing, including downloading of attachments. Prevents multiple syncs
 * from running in parallel by building a queue and intelligently merging sync
 * requests.
 * Examples: Enqueuing a WithoutAttachments sync removes a SendOnly sync from the
 * queue. A running SendOnly sync would be cancelled. Enqueuing a SendOnly sync
 * while a WithoutAttachments sync is running or enqueued will do nothing.
 * Enqueuing an Everything sync will remove all attachment download requests from
 * the queue.
 */
@interface KASyncer : NSObject

/** Set or replace the SyncerListener which should receive sync events. */
- (void)setListener:(nullable id<KASyncerListener>)listener;

/** Request that the data specified in mode is synced. */
- (void)requestSync:(KASyncMode)mode;

/** Request that all attachments for the given message are downloaded. */
- (void)requestDownloadingAttachmentsForMessage:(int64_t)msgId;

/**
 * Gets an AsyncTask that can be used for cancellation or waiting. It affects
 * both running and queued jobs. Releasing it will not cancel the job
 * automatically.
 */
- (nullable KAAsyncTask *)asyncTask;

@end
