// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

#include "kulloclient/api/SyncerListener.h"
#include <kulloclient/nn.h>
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol KASyncerListener;

namespace ObjCpp { namespace Kullo { namespace Api {

class SyncerListener
{
public:
    using CppType = ::Kullo::nn_shared_ptr<::Kullo::Api::SyncerListener>;
    using CppOptType = std::shared_ptr<::Kullo::Api::SyncerListener>;
    using ObjcType = id<KASyncerListener>;

    using Boxed = SyncerListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

