// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "KASyncMode.h"
#import <Foundation/Foundation.h>
@class KAAsyncTask;
@protocol KASyncerRunListener;


@interface KASyncer : NSObject

/** Synchronize messages etc. with the server. */
- (nullable KAAsyncTask *)runAsync:(KASyncMode)mode
                          listener:(nullable id<KASyncerRunListener>)listener;

/** Download all attachments for a given message */
- (nullable KAAsyncTask *)downloadAttachmentsForMessageAsync:(int64_t)msgId
                                                    listener:(nullable id<KASyncerRunListener>)listener;

@end
