// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#include "kulloclient/api/TaskRunner.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol KATaskRunner;

namespace ObjCpp { namespace Kullo { namespace Api {

class TaskRunner
{
public:
    using CppType = std::shared_ptr<::Kullo::Api::TaskRunner>;
    using ObjcType = id<KATaskRunner>;

    using Boxed = TaskRunner;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

