// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from taskrunner.djinni

#import <Foundation/Foundation.h>
@class KATask;


@protocol KATaskRunner

/**
 * Runs the given task asynchronously (simplest case: in a new thread)
 * and returns immediately.
 */
- (void)runTaskAsync:(nullable KATask *)task;

@end
