// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import <Foundation/Foundation.h>


/**
 * A task that libkullo wants to be executed asynchronously. It is passed to
 * TaskRunner.
 */
@interface KATask : NSObject

/** Must not be called from the UI thread. */
- (void)run;

@end
