// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from taskrunner.djinni

#include "kulloclient/api/Task.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KATask;

namespace ObjCpp { namespace Kullo { namespace Api {

class Task
{
public:
    using CppType = std::shared_ptr<::Kullo::Api::Task>;
    using CppOptType = std::shared_ptr<::Kullo::Api::Task>;
    using ObjcType = KATask*;

    using Boxed = Task;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

