// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#include "kulloclient/api/UserSettings.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class KAUserSettings;

namespace ObjCpp { namespace Kullo { namespace Api {

class UserSettings
{
public:
    using CppType = std::shared_ptr<::Kullo::Api::UserSettings>;
    using ObjcType = KAUserSettings*;

    using Boxed = UserSettings;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);

private:
    class ObjcProxy;
};

} } }  // namespace ObjCpp::Kullo::Api

